### ISSUE TITLE
建议订阅放在显眼处

### ISSUE THREAD

**Issue by wsa01378** [ProxyPanel/ProxyPanel#100]
作为新用户过来，找订阅地址找了大半天。心想不会连订阅都没有吧
最后发现竟然在帮助中心里。这绝对是'万万没想到'

订阅放在个人主页显眼处合适些。可以的话加个一键复制clash订阅就更完美；
另外ssrpanel的订阅二维码功能给ios用户挺有用；

wiki安装教程提示下读者，管理员用户名&密码是
test@test.com
123456

**Comment by ZBrettonYe** [comment]
订阅位置看后期开发订阅情况；
clash订阅 在开发；
wiki 已改；
