### ISSUE TITLE
强制访问百度问题

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#105]
描述：
1、一级域名a.com,下有2个二级域名为www.a.com，sub.a.com 
2、一级域名b.com，下有1个一级域名为www.b.com（作为备用域名使用）

问题：
1、设置网站地址为a.com，订阅地址不改变默认（即为不去碰），访问a.com，www.a.com，sub.a.ocm 和备用域名均正常使用；
2、设置网站地址为a.com，订阅地址改变为sub.a.ocm，访问a.com，sub.a.com和备用域名都强制跳转百度

**Comment by ZBrettonYe** [comment]
不解决；
这个问题有点无聊，首先节点订阅地址是为了防止主要域名被墙，导致订阅也失效提供的。正常情况下是叫你用其他域名 比如 sub.a.cf / sub.a.net 之类的；
你这个sub.a.com设置的就有点鸡助；

其实你明明可以用www.a.com作为面板域名，再把a.com做转跳到www.a.com； 这样a.com 的泛域名就不会影响到下面的子域名了；

**Comment by zixinote** [comment]
> 不解决；
> 这个问题有点无聊，首先节点订阅地址是为了防止主要域名被墙，导致订阅也失效提供的。正常情况下是叫你用其他域名 比如 sub.a.cf / sub.a.net 之类的；
> 你这个sub.a.com设置的就有点鸡助；
> 
> 其实你明明可以用www.a.com作为面板域名，再把a.com做转跳到www.a.com； 这样a.com 的泛域名就不会影响到下面的子域名了；

我又何尝不知道，只是早期遗留的问题，万人大机场

**Comment by ZBrettonYe** [comment]
访问：
proxypanel.ml
demo.proxypanel.ml
sub.proxypanel.ml

简单网站设置 就可以跳过这个问题
