### ISSUE TITLE
用户分组无效

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#113]
**描述你遇到的bug**
问题：1、2节点分配对应V1，V2两个等级，都分配到A用户组；
1、用户设置等级free归类到A用户组，订阅无法获取节点；
2、用户设置等级V1，归类到A用户组，订阅返回节点1；
3、用户设置等级V2，归类到A用户组，订阅返回节点2；

**Comment by ZBrettonYe** [comment]
然后问题呢？

**Comment by zixinote** [comment]
> 然后问题呢？

分组不应该按照等级吧，已经有等级了？归类到那个组，就可以使用任意组的节点
