### ISSUE TITLE
最新master分支问题

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#116]
1、保存节点卡死
2、当前版本vnet协议无法链接
3、管理超时后刷新页面提示重定向过多
4、注册账号没有勾选同意协议，里面多语言不完整
5、什么时候请求币安的API了？（下图）
![image](https://user-images.githubusercontent.com/63467104/103911105-95ec9a00-5140-11eb-974f-1e68e1ae0587.png)

**Comment by ZBrettonYe** [comment]
大部分都没法解决，要么就是提供的信息太少了。
