### ISSUE TITLE
关于限速和设备数的建议

### ISSUE THREAD

**Issue by cmtomkan310** [ProxyPanel/ProxyPanel#117]
**功能描述 | Feature request description**
根据商品增加限速字段和设备数字段

**相关资料/想法 | Related documents**

就目前的限速来说，除单节点限速，限设备数外，只能进用户管理界面手动修改。
如通过商品来控制，会提高整个面板的使用性。
而现在这种模式，如节点限速10M，设备数20M，第21个用户无法使用，现在这种设置也存在一个弊端，就是无法做到不同等级用户对同一个节点的使用限定。

如购买VIP-1套餐，除现有字段外，增加限速和设备数，用户购买此套餐，自动限定了使用范围。

**Comment by ZBrettonYe** [comment]
看不懂
