### ISSUE TITLE
请求在订阅管理查看订阅记录中增加IP归属地显示

### ISSUE THREAD

**Issue by ligongfu** [ProxyPanel/ProxyPanel#121]
**功能描述 | Feature request description**
Bretton大佬，在线IP监控有显示归属地，订阅记录咱也显示一个呗？
**相关资料/想法 | Related documents**
by the way,我有个更大胆的想法

请求添加订阅异常提醒功能，例如用户订阅IP为北京，突然从南京的IP订阅了，则提醒管理员/用户

**Comment by ZBrettonYe** [comment]
第一点可以有；

第二点鸡助，首先用户会出现在使用开启代理的情况下更新订阅，这会出现误报；要排除这个你就需要依次排除你线路的IP，为了这点鸡助功能面板还要不停巡察节点IP变动并记录来保证一个白名单。这个对动态IP的线路不友善

**Comment by ligongfu** [comment]
> 第一点可以有；
> 
> 第二点鸡助，首先用户会出现在使用开启代理的情况下更新订阅，这会出现误报；要排除这个你就需要依次排除你线路的IP，为了这点鸡助功能面板还要不停巡察节点IP变动并记录来保证一个白名单。这个对动态IP的线路不友善

只是供 管理员/用户 进行人工判断，主要是为了防止订阅信息 滥用/泄漏
