### ISSUE TITLE
后台节点列表如果是中转节点，类型会显示为中转

### ISSUE THREAD

**Issue by ligongfu** [ProxyPanel/ProxyPanel#122]
**描述你遇到的bug**
简单的描述一下你遇到的bug
后台节点列表如果是中转节点，类型会显示为中转
**如何复现你的BUG**
为方便找bug，请说明你bug产生的步骤

**截图**

**Comment by ZBrettonYe** [comment]
问题呢?

**Comment by ligongfu** [comment]
> 问题呢?

好吧，我以为能Get到

是不是中转节点，类型都不应该显示中转，不是吗？
更合理的方式是新增显示是否为中转节点，而类型仍然显示为 Shadowsocks(R) / V2Ray / Trojan / VNET

**Comment by ZBrettonYe** [comment]
原文其详，听的有点迷糊

**Comment by ligongfu** [comment]
> 原文其详，听的有点迷糊

节点类型取值范围： Shadowsocks(R) / V2Ray / Trojan / VNET
是否中转：True / flase

![QQ截图20210112113549](https://user-images.githubusercontent.com/33894625/104266482-a8f9c400-54ca-11eb-941d-96db36c2ccb1.jpg)
![QQ截图20210112113742](https://user-images.githubusercontent.com/33894625/104266489-abf4b480-54ca-11eb-822b-f413c77acc8c.jpg)
