### ISSUE TITLE
添加节点->提交后页面卡死

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#123]
**描述你遇到的bug**
刚开始添加第一个节点还成功，后面在添加节点提交后，就导致页面卡住了。返回错误如下图，图1编辑节点，等待一段时间返回图2的日志，图3是添加卡住后，新开页面获取的日志

**截图**
图1
![image](https://user-images.githubusercontent.com/63467104/104115078-4e375f80-5346-11eb-9e07-12898386021c.png)
图2
![image](https://user-images.githubusercontent.com/63467104/104115318-fa7a4580-5348-11eb-9929-8296ba0817e9.png)
图3
![image](https://user-images.githubusercontent.com/63467104/104115279-a40d0700-5348-11eb-99f8-09b46249a2d2.png)

**Comment by ZBrettonYe** [comment]
自己操作不当，看提示 【重载节点】推送异常;

可以尝试在demo重现该问题

**Comment by zixinote** [comment]
> 自己操作不当，看提示 【重载节点】推送异常;
> 
> 可以尝试在demo重现该问题

1、这是demo站重现的错误信息，我按正常的配置去填写一样的行为操作，没有图1、2、3的日志，但是整个页面卡住，提交后没有成功或错误的提示返回，浏览器chrome。
2、如果同时打开日志页面，节点页面，点击“提交”步骤进行保存的同时，日志页面也会卡住

**Comment by ZBrettonYe** [comment]
恩，的确有问题，在看了
