### ISSUE TITLE
商品购买严重bug

### ISSUE THREAD

**Issue by 110560** [ProxyPanel/ProxyPanel#124]
用户购买套餐时 点击余额支付  卡在这个余额支付的页面，然后点击主页  账号状态停用 未知原因

再次充值再次购买后正常  严重bug。

还有演示站
 商品编辑完成之后点提交 
套餐包含流量直接变成0。。。
严重bug，请修复

**Comment by 110560** [comment]
同一件商品 
第1次购买后在账单里面的结果。
  和第2次购买后在账单里面的结果  如图...第1次购买的结果有毛病

![IMG_20210111_124338](https://user-images.githubusercontent.com/32481672/104147826-d5e6a200-540a-11eb-9099-9e85160a28ce.jpg)
![IMG_20210111_124413](https://user-images.githubusercontent.com/32481672/104147827-d8e19280-540a-11eb-8e0d-a3d936e3b1ce.jpg)

**Comment by 110560** [comment]
第1次购买商品后
账单如下图
主页如下图
![IMG_20210111_124338](https://user-images.githubusercontent.com/32481672/104147972-5f966f80-540b-11eb-9e82-becac8e61141.jpg)
![IMG_20210111_124804](https://user-images.githubusercontent.com/32481672/104147975-62916000-540b-11eb-8d70-50ff17fcf64d.jpg)

**Comment by 110560** [comment]
第1次购买时 点击余额支付。 网站页面卡顿没有任何返回信息，点击刷新也没用  过了一两分钟才能正常刷新网站

**Comment by ZBrettonYe** [comment]
> 商品编辑完成之后点提交
> 套餐包含流量直接变成0。。。

无法重现；请重新尝试操作流程；


> 第1次购买时 点击余额支付。 网站页面卡顿没有任何返回信息，点击刷新也没用 过了一两分钟才能正常刷新网站
出现卡顿现在原因还未知；

**Comment by 110560** [comment]
![Screenshot_2021-01-11-16-10-26-718_com android chrome](https://user-images.githubusercontent.com/32481672/104158076-8c588000-5427-11eb-809f-ce5c18217582.jpg)
流量单位为MB时  填入进去提交就会如图  
流量单位为GB时 一切正常。 测试完成。
测试环境演示站。

**Comment by 110560** [comment]
![Uploading Screenshot_2021-01-11-16-13-44-514_com.android.chrome.jpg…]()
点击余额支付之后卡顿  套餐无法正常赋予给用户
需要再次购买之后才能正常赋予给用户。

**Comment by 110560** [comment]
点击余额支付之后卡顿 套餐无法正常赋予给用户
需要再次购买之后才能正常赋予给用户
![Screenshot_2021-01-11-16-13-44-514_com android chrome](https://user-images.githubusercontent.com/32481672/104158479-67184180-5428-11eb-83e2-59e49e9b2f5a.jpg)

**Comment by ZBrettonYe** [comment]
> 流量单位为MB时 填入进去提交就会如图
> 流量单位为GB时 一切正常。 测试完成。
> 测试环境演示站。

早这样解释不就好了，问题找到了

**Comment by 110560** [comment]
> > 流量单位为MB时 填入进去提交就会如图
> > 流量单位为GB时 一切正常。 测试完成。
> > 测试环境演示站。
> 
> 早这样解释不就好了，问题找到了

我也是看了你的回复，然后我再去测试的时候才发现对比出来的....
购买套餐的那个修好了吗
