### ISSUE TITLE
订阅客户端支持

### ISSUE THREAD

**Issue by Draco-china** [ProxyPanel/ProxyPanel#127]
**功能描述 | Feature request description**
希望支持支持 clash \ surge 客户端
V2rayN，V2rayU等客户端只不支持trojan的订阅
ShadowSock 等客户端 某些平台都已经停止更新和维护
clash\surge GUI 多平台支持且协议支持相对完善
**相关资料/想法 | Related documents**
订阅规则转化相关 https://github.com/KOP-XIAO/QuantumultX-Surge-API

**Comment by ZBrettonYe** [comment]
麻烦先了解了本面板，再发言
