### ISSUE TITLE
触发审计规则自动跳转网页

### ISSUE THREAD

**Issue by bickernwong** [ProxyPanel/ProxyPanel#128]
**功能描述 | Feature request description**
触发审计规则自动跳转网页，以减少因涉政治带来的风险。
**相关资料/想法 | Related documents**
以下为网页警告内容
请务必保护好自己 我们自认为打破了信息的壁垒，其实打破的是保护我们的屏障。因为外网真的存在很多误导性言论，来自各个利益集团对中国网民疯狂洗脑，他们往往还喜欢以民主平等自由等旗号自称，但仔细想想真的是这样吗？我只知道美国是最善于运用舆论的国家，会结合大数据潜移默化地改变你的观念。如果大家在上网过程中不经意看到了某些观点，务必保留自己独立思考的能力，如果你是一个容易被带偏的人，则建议回到屏障之中。

本网站只提供给大家用于更便捷地学习工作和娱乐。如果你是对上述观点持反对意见的极端政治人士，或者已被洗脑，请立即离开，本网站不对你开放。

**Comment by ZBrettonYe** [comment]
这不属于面板范畴，归后端管
