### ISSUE TITLE
麻瓜对接后 提示创建订单错误

### ISSUE THREAD

**Issue by cnmars** [ProxyPanel/ProxyPanel#129]
**描述你遇到的bug**
简单的描述一下你遇到的bug
[2021-01-21 17:10:07] production.WARNING: 创建订单错误：array (
  'status' => 400,
  'error_code' => 'PAY_PRICE_ERROR',
  'error' => 'Price amount or currency is not set correctly.',
)
**如何复现你的BUG**
为方便找bug，请说明你bug产生的步骤

**截图**

**Comment by ZBrettonYe** [comment]
没有测试账号，其次你这个消息里涉及的问题代码里都没有问题；
