### ISSUE TITLE
新建节点后修改任意内容后点提交就会出现报错

### ISSUE THREAD

**Issue by xb0or** [ProxyPanel/ProxyPanel#13]
**描述你遇到的bug**
Unable to parse URI: 1.1.1.1:0

**如何复现你的BUG**
新建节点后修改任意内容后点提交就会出现报错

**截图**
![image](https://user-images.githubusercontent.com/57210034/93002481-ea7f6000-f526-11ea-8e60-b08527804c1a.png)

**Comment by ZBrettonYe** [comment]
用vnet的话，麻烦编辑前先确保vnet有用
