### ISSUE TITLE
商品编辑页面内容丢失

### ISSUE THREAD

**Issue by yesisbug** [ProxyPanel/ProxyPanel#134]
**描述你遇到的bug**
1、添加商品成功后，自动刷新页面后，部分内容丢失；
2、编辑商品也是部分内容丢失；

**如何复现你的BUG**
demo站复现

**Comment by ZBrettonYe** [comment]
截图呢？

**Comment by ZBrettonYe** [comment]
内容丢失什么东西，测了没丢失任何东西

**Comment by zixinote** [comment]
> 内容丢失什么东西，测了没丢失任何东西

点进去看看里面的内容还在不在

**Comment by ZBrettonYe** [comment]
所以都说了，要这么复现。早说早搞不就好了。

**Comment by zixinote** [comment]
> 内容丢失什么东西，测了没丢失任何东西

添加商品，当自定义列表的<li></li>大于等于2个的时候保存后，编辑页面内容丢失

**Comment by zixinote** [comment]
这么快修复了。。。。
