### ISSUE TITLE
流量用尽的情况下，封禁无效

### ISSUE THREAD

**Issue by gitject** [ProxyPanel/ProxyPanel#135]
**描述你遇到的bug**
单纯的流量用尽，账号时间没到期的情况下，面板显示已经封禁了，仅是无法再订阅更新，但是原有的线路依然能使用。

**截图**
![image](https://user-images.githubusercontent.com/31369527/105735191-60ccae00-5f6e-11eb-9a23-1fb33b6afa85.png)
![image](https://user-images.githubusercontent.com/31369527/105735238-6de99d00-5f6e-11eb-8c4d-2145bf9cdb0f.png)

**Comment by ZBrettonYe** [comment]
什么后端

**Comment by gitject** [comment]
v2ray-poseidon

**Comment by ZBrettonYe** [comment]
看后端日志自行判断
