### ISSUE TITLE
用户邮箱激活会报500错误

### ISSUE THREAD

**Issue by cnmars** [ProxyPanel/ProxyPanel#140]
**描述你遇到的bug**
简单的描述一下你遇到的bug
1、有时候会点前端设置页面没反应  无法复现
2、邮箱激活 问题  注册前 会显示发送失败  邮箱设置没问题   注册后激活 会报500错误 

请管理员有时间可以看看

**如何复现你的BUG**
为方便找bug，请说明你bug产生的步骤

**截图**

**Comment by ZBrettonYe** [comment]
麻烦把报错的日志贴上

**Comment by ZBrettonYe** [comment]
2个问题都无法复现

**Comment by cnmars** [comment]
![截屏2021-01-27 下午3.38.45.png](https://i.loli.net/2021/01/27/Wa8R9VZEnHwygGp.png)
本来要重新安装 在试试 不过 又发现这个报错
