### ISSUE TITLE
[BUG]MAC clashX订阅 会报这个错误 

### ISSUE THREAD

**Issue by cnmars** [ProxyPanel/ProxyPanel#142]
MAC clashX订阅 会报这个错误 使用订阅转换平台转换默认订阅没问题

浏览器直接打开如下

mixed-port: 7890 allow-lan: true bind-address: '*' mode: rule log-level: info external-controller: '127.0.0.1:9090' dns: enable: true ipv6: false default-nameserver: [223.5.5.5, 119.29.29.29] enhanced-mode: redir-host fake-ip-range: 198.18.0.1/16 use-hosts: true nameserver: ['https://doh.pub/dns-query'] fallback: ['tls://1.0.0.1:853', 'https://cloudflare-dns.com/dns-query', 'https://dns.google/dns-query'] fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] } proxies: - { name: 'HongKong 01', type: vmess, server: node.xyz, port: 5000, uuid: e8187956-cb75-418b-8f35-0580d4bd49cb, alterId: 16, cipher: auto, udp: 0, network: ws, ws-path: /1cgom7xrgkb6y1cm, ws-headers: { Host: null } } - 此后省略

**错误截图**
![截屏2021-01-29 上午6.54.48.png](https://i.loli.net/2021/01/29/q4RXTHOUbwEhg1y.png)

**信息**
- 面板版本：[例如 Release 2.6.d]

**额外信息**

**Comment by ZBrettonYe** [comment]
那就说明面板不支持clashX

**Comment by bickernwong** [comment]
嗯推荐使用https://github.com/HMBSbige/ShadowsocksR-Windows/releases
