### ISSUE TITLE
[BUG]邮件投递没有记录

### ISSUE THREAD

**Issue by gitject** [ProxyPanel/ProxyPanel#143]
**错误描述**
邮件投递能正常发出，日志没报错，有收到邮件，但是邮件投递里没有记录。

**错误截图**
![image](https://user-images.githubusercontent.com/31369527/106248896-9c0bfd00-624c-11eb-8156-c29a9b003f99.png)
![image](https://user-images.githubusercontent.com/31369527/106249007-be057f80-624c-11eb-9804-fe619b240e39.png)
![image](https://user-images.githubusercontent.com/31369527/106249165-f7d68600-624c-11eb-8b9d-476b9493f046.png)

**信息**
- 面板版本：[Release 2.6.0]

**Comment by ZBrettonYe** [comment]
Release 2.6.0 新版通知系统不再用邮件投递日志作为报错标准

**Comment by gitject** [comment]
不是投递日志报错，是邮件发出去了，但是没有发送的记录。
