### ISSUE TITLE
[BUG]节点使用报告--邮件，ServerChan发送都失效

### ISSUE THREAD

**Issue by gitject** [ProxyPanel/ProxyPanel#144]
**错误描述**
节点使用报告，使用邮件，ServerChan发送都失效。

邮件，已经配置号管理员邮箱，且账号过期的邮件，能正常发送。
ServerChan，已经在设置里填写SCKEY，且点击 发送测试消息 ，能正确收到推送。

但是在设置的 节点使用报告 分别选项 邮件 或者 ServerChan 都发送失败。

**日志**
邮件发送：
View [mail.node.dailyReport] not found. {"exception":"[object] (InvalidArgumentException(code: 0): View [mail.node.dailyReport] not found. at /www/wwwroot/demo.com/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137)
异常来源InvalidArgumentException

ServerChan发送：
Driver [serverChan] not supported. {"exception":"[object] (InvalidArgumentException(code: 0): Driver [serverChan] not supported. at /www/wwwroot/demo.com/vendor/laravel/framework/src/Illuminate/Support/Manager.php:119)
异常来源InvalidArgumentException

**信息**
- 面板版本：[ Release 2.6.0]

**Comment by ZBrettonYe** [comment]
重启你的服务器，更新你的缓存；

否者就是你的版本错误了，Release 2.6.0 不再用mail.node.dailyReport这个文件了
