### ISSUE TITLE
quantumult订阅仅支持ssr，不支持自有的v2ray订阅格式

### ISSUE THREAD

**Issue by Rumor404** [ProxyPanel/ProxyPanel#148]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述 | Feature request description**
简明扼要地描述需要的功能

quantumult仅订阅支持ssr，不支持**自有的v2ray订阅格式**，希望作者支持

**相关资料/额外想法 | Related documents**

可参考 v2board 进行改写，下方代码链接
https://github.com/v2board/v2board/blob/master/app/Http/Controllers/Client/ClientController.php

**Comment by ZBrettonYe** [comment]
不知道具体说啥子，改写个大头，这部分早就写了，麻烦先了解代码再提意见
