### ISSUE TITLE
更新订阅失败

### ISSUE THREAD

**Issue by ChuJian2** [ProxyPanel/ProxyPanel#149]
在使用手机上的V2rayng等软件时会订阅失败

**Comment by ChuJian2** [comment]
PC段没有问题，手机上订阅以及单个vmess链接导入都失败

**Comment by ZBrettonYe** [comment]
都是什么客户端

**Comment by ZBrettonYe** [comment]
请提供对应客户端更新后 https://demo.proxypanel.ml/admin/subscribe 的订阅日志

**Comment by ChuJian2** [comment]
您好，很高兴能得到你的回答，在之前我使用自己的链接得到无法访问的结果，于是我更换了前端，因此很抱歉我现在无法使用我的链接来验证，但是刚刚使用您的示例站是可以正常进行订阅的，因此这个问题多半是我自己的原因，我现在重新自己搭建并测试。
此外，之前所说的客户端分别如下：
PC端：QV2ray 可以正常进行订阅
手机端：v2rayng 无法正常订阅
              BifrostV 可以正常进行订阅

**Comment by ChuJian2** [comment]
重新搭建2.6.0版后发现不可以订阅，然后发现是vmess链接的问题，订阅通过base64解码是可以转换为vmess链接的，但是vmess链接在上述客户端中的V2rayng识别不出来，我想使用master版，搭建出错。

**Comment by ChuJian2** [comment]
安装master版时，导入数据库php artisan migrate --seed时提示
![Uploading QQ截图20210211153218.png…]()

**Comment by ChuJian2** [comment]
生成如下列链接：
vmess://eyJ2IjoiMiIsInBzIjoidGVzdCIsImFkZCI6InRlc3QuY29tIiwicG9ydCI6MTAwNTMsImlkIjoiZjc2ZTk4ZTktNjQ1OC00NjRjLThjN2EtOWU5NTQxYzMzNDU0IiwiYWlkIjoxNiwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsImhvc3QiOm51bGwsInBhdGgiOiJcL2xyajFnajNxbG1kcWRqbWkiLCJ0bHMiOiIifQ==
在QV2ray可以导入，在v2rayng无法导入

**Comment by ZBrettonYe** [comment]
请提供对应客户端更新后 https://demo.proxypanel.ml/admin/subscribe 的订阅日志

**Comment by ChuJian2** [comment]
--------- beginning of main
02-13 10:06:51.123 W/System.err(10464): java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter <set-?>
02-13 10:06:51.123 W/System.err(10464): 	at com.v2ray.ang.dto.AngConfig$VmessBean.setRequestHost(AngConfig.kt)
02-13 10:06:51.123 W/System.err(10464): 	at com.v2ray.ang.util.AngConfigManager.importConfig(AngConfigManager.kt:314)
02-13 10:06:51.123 W/System.err(10464): 	at com.v2ray.ang.util.AngConfigManager.importBatchConfig(AngConfigManager.kt:883)
02-13 10:06:51.123 W/System.err(10464): 	at com.v2ray.ang.ui.MainActivity.importBatchConfig(MainActivity.kt:391)
02-13 10:06:51.123 W/System.err(10464): 	at com.v2ray.ang.ui.MainActivity.importBatchConfig$default(MainActivity.kt:390)
02-13 10:06:51.123 W/System.err(10464): 	at com.v2ray.ang.ui.MainActivity.importClipboard(MainActivity.kt:382)
02-13 10:06:51.123 W/System.err(10464): 	at com.v2ray.ang.ui.MainActivity.onOptionsItemSelected(MainActivity.kt:222)
02-13 10:06:51.123 W/System.err(10464): 	at android.app.Activity.onMenuItemSelected(Activity.java:3256)
02-13 10:06:51.123 W/System.err(10464): 	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:383)
02-13 10:06:51.123 W/System.err(10464): 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:228)
02-13 10:06:51.123 W/System.err(10464): 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
02-13 10:06:51.123 W/System.err(10464): 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
02-13 10:06:51.123 W/System.err(10464): 	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
02-13 10:06:51.123 W/System.err(10464): 	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
02-13 10:06:51.123 W/System.err(10464): 	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:779)
02-13 10:06:51.123 W/System.err(10464): 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
02-13 10:06:51.123 W/System.err(10464): 	at androidx.appcompat.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:91)
02-13 10:06:51.123 W/System.err(10464): 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
02-13 10:06:51.123 W/System.err(10464): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
02-13 10:06:51.123 W/System.err(10464): 	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
02-13 10:06:51.123 W/System.err(10464): 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
02-13 10:06:51.123 W/System.err(10464): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1156)
02-13 10:06:51.123 W/System.err(10464): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3128)
02-13 10:06:51.124 W/System.err(10464): 	at android.widget.AbsListView$3.run(AbsListView.java:4043)
02-13 10:06:51.124 W/System.err(10464): 	at android.os.Handler.handleCallback(Handler.java:751)
02-13 10:06:51.124 W/System.err(10464): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-13 10:06:51.124 W/System.err(10464): 	at android.os.Looper.loop(Looper.java:154)
02-13 10:06:51.124 W/System.err(10464): 	at android.app.ActivityThread.main(ActivityThread.java:6227)
02-13 10:06:51.124 W/System.err(10464): 	at java.lang.reflect.Method.invoke(Native Method)
02-13 10:06:51.124 W/System.err(10464): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
02-13 10:06:51.124 W/System.err(10464): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:797)
02-13 10:06:51.124 W/System.err(10464): java.lang.IllegalArgumentException: bad base-64
02-13 10:06:51.127 W/System.err(10464): 	at android.util.Base64.decode(Base64.java:161)
02-13 10:06:51.127 W/System.err(10464): 	at android.util.Base64.decode(Base64.java:136)
02-13 10:06:51.127 W/System.err(10464): 	at android.util.Base64.decode(Base64.java:118)
02-13 10:06:51.127 W/System.err(10464): 	at com.v2ray.ang.util.Utils.decode(Utils.kt:98)
02-13 10:06:51.127 W/System.err(10464): 	at com.v2ray.ang.ui.MainActivity.importBatchConfig(MainActivity.kt:393)
02-13 10:06:51.127 W/System.err(10464): 	at com.v2ray.ang.ui.MainActivity.importBatchConfig$default(MainActivity.kt:390)
02-13 10:06:51.127 W/System.err(10464): 	at com.v2ray.ang.ui.MainActivity.importClipboard(MainActivity.kt:382)
02-13 10:06:51.127 W/System.err(10464): 	at com.v2ray.ang.ui.MainActivity.onOptionsItemSelected(MainActivity.kt:222)
02-13 10:06:51.127 W/System.err(10464): 	at android.app.Activity.onMenuItemSelected(Activity.java:3256)
02-13 10:06:51.127 W/System.err(10464): 	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:383)
02-13 10:06:51.127 W/System.err(10464): 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:228)
02-13 10:06:51.127 W/System.err(10464): 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
02-13 10:06:51.127 W/System.err(10464): 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
02-13 10:06:51.127 W/System.err(10464): 	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
02-13 10:06:51.127 W/System.err(10464): 	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
02-13 10:06:51.127 W/System.err(10464): 	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:779)
02-13 10:06:51.127 W/System.err(10464): 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
02-13 10:06:51.128 W/System.err(10464): 	at androidx.appcompat.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:91)
02-13 10:06:51.128 W/System.err(10464): 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
02-13 10:06:51.128 W/System.err(10464): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
02-13 10:06:51.128 W/System.err(10464): 	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
02-13 10:06:51.128 W/System.err(10464): 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
02-13 10:06:51.128 W/System.err(10464): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1156)
02-13 10:06:51.128 W/System.err(10464): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3128)
02-13 10:06:51.128 W/System.err(10464): 	at android.widget.AbsListView$3.run(AbsListView.java:4043)
02-13 10:06:51.128 W/System.err(10464): 	at android.os.Handler.handleCallback(Handler.java:751)
02-13 10:06:51.128 W/System.err(10464): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-13 10:06:51.128 W/System.err(10464): 	at android.os.Looper.loop(Looper.java:154)
02-13 10:06:51.128 W/System.err(10464): 	at android.app.ActivityThread.main(ActivityThread.java:6227)
02-13 10:06:51.128 W/System.err(10464): 	at java.lang.reflect.Method.invoke(Native Method)
02-13 10:06:51.128 W/System.err(10464): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
02-13 10:06:51.128 W/System.err(10464): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:797)

**Comment by ZBrettonYe** [comment]
> --------- beginning of main
> 02-13 10:06:51.123 W/System.err(10464): java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter <set-?>
> 02-13 10:06:51.123 W/System.err(10464): at com.v2ray.ang.dto.AngConfig$VmessBean.setRequestHost(AngConfig.kt)
> 02-13 10:06:51.123 W/System.err(10464): at com.v2ray.ang.util.AngConfigManager.importConfig(AngConfigManager.kt:314)
> 02-13 10:06:51.123 W/System.err(10464): at com.v2ray.ang.util.AngConfigManager.importBatchConfig(AngConfigManager.kt:883)
> 02-13 10:06:51.123 W/System.err(10464): at com.v2ray.ang.ui.MainActivity.importBatchConfig(MainActivity.kt:391)
> 02-13 10:06:51.123 W/System.err(10464): at com.v2ray.ang.ui.MainActivity.importBatchConfig$default(MainActivity.kt:390)
> 02-13 10:06:51.123 W/System.err(10464): at com.v2ray.ang.ui.MainActivity.importClipboard(MainActivity.kt:382)
> 02-13 10:06:51.123 W/System.err(10464): at com.v2ray.ang.ui.MainActivity.onOptionsItemSelected(MainActivity.kt:222)
> 02-13 10:06:51.123 W/System.err(10464): at android.app.Activity.onMenuItemSelected(Activity.java:3256)
> 02-13 10:06:51.123 W/System.err(10464): at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:383)
> 02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:228)
> 02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
> 02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
> 02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
> 02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
> 02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:779)
> 02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
> 02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:91)
> 02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
> 02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
> 02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
> 02-13 10:06:51.123 W/System.err(10464): at android.widget.AdapterView.performItemClick(AdapterView.java:310)
> 02-13 10:06:51.123 W/System.err(10464): at android.widget.AbsListView.performItemClick(AbsListView.java:1156)
> 02-13 10:06:51.123 W/System.err(10464): at android.widget.AbsListView$PerformClick.run(AbsListView.java:3128)
> 02-13 10:06:51.124 W/System.err(10464): at android.widget.AbsListView$3.run(AbsListView.java:4043)
> 02-13 10:06:51.124 W/System.err(10464): at android.os.Handler.handleCallback(Handler.java:751)
> 02-13 10:06:51.124 W/System.err(10464): at android.os.Handler.dispatchMessage(Handler.java:95)
> 02-13 10:06:51.124 W/System.err(10464): at android.os.Looper.loop(Looper.java:154)
> 02-13 10:06:51.124 W/System.err(10464): at android.app.ActivityThread.main(ActivityThread.java:6227)
> 02-13 10:06:51.124 W/System.err(10464): at java.lang.reflect.Method.invoke(Native Method)
> 02-13 10:06:51.124 W/System.err(10464): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
> 02-13 10:06:51.124 W/System.err(10464): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:797)
> 02-13 10:06:51.124 W/System.err(10464): java.lang.IllegalArgumentException: bad base-64
> 02-13 10:06:51.127 W/System.err(10464): at android.util.Base64.decode(Base64.java:161)
> 02-13 10:06:51.127 W/System.err(10464): at android.util.Base64.decode(Base64.java:136)
> 02-13 10:06:51.127 W/System.err(10464): at android.util.Base64.decode(Base64.java:118)
> 02-13 10:06:51.127 W/System.err(10464): at com.v2ray.ang.util.Utils.decode(Utils.kt:98)
> 02-13 10:06:51.127 W/System.err(10464): at com.v2ray.ang.ui.MainActivity.importBatchConfig(MainActivity.kt:393)
> 02-13 10:06:51.127 W/System.err(10464): at com.v2ray.ang.ui.MainActivity.importBatchConfig$default(MainActivity.kt:390)
> 02-13 10:06:51.127 W/System.err(10464): at com.v2ray.ang.ui.MainActivity.importClipboard(MainActivity.kt:382)
> 02-13 10:06:51.127 W/System.err(10464): at com.v2ray.ang.ui.MainActivity.onOptionsItemSelected(MainActivity.kt:222)
> 02-13 10:06:51.127 W/System.err(10464): at android.app.Activity.onMenuItemSelected(Activity.java:3256)
> 02-13 10:06:51.127 W/System.err(10464): at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:383)
> 02-13 10:06:51.127 W/System.err(10464): at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:228)
> 02-13 10:06:51.127 W/System.err(10464): at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
> 02-13 10:06:51.127 W/System.err(10464): at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
> 02-13 10:06:51.127 W/System.err(10464): at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
> 02-13 10:06:51.127 W/System.err(10464): at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
> 02-13 10:06:51.127 W/System.err(10464): at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:779)
> 02-13 10:06:51.127 W/System.err(10464): at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
> 02-13 10:06:51.128 W/System.err(10464): at androidx.appcompat.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:91)
> 02-13 10:06:51.128 W/System.err(10464): at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
> 02-13 10:06:51.128 W/System.err(10464): at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
> 02-13 10:06:51.128 W/System.err(10464): at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
> 02-13 10:06:51.128 W/System.err(10464): at android.widget.AdapterView.performItemClick(AdapterView.java:310)
> 02-13 10:06:51.128 W/System.err(10464): at android.widget.AbsListView.performItemClick(AbsListView.java:1156)
> 02-13 10:06:51.128 W/System.err(10464): at android.widget.AbsListView$PerformClick.run(AbsListView.java:3128)
> 02-13 10:06:51.128 W/System.err(10464): at android.widget.AbsListView$3.run(AbsListView.java:4043)
> 02-13 10:06:51.128 W/System.err(10464): at android.os.Handler.handleCallback(Handler.java:751)
> 02-13 10:06:51.128 W/System.err(10464): at android.os.Handler.dispatchMessage(Handler.java:95)
> 02-13 10:06:51.128 W/System.err(10464): at android.os.Looper.loop(Looper.java:154)
> 02-13 10:06:51.128 W/System.err(10464): at android.app.ActivityThread.main(ActivityThread.java:6227)
> 02-13 10:06:51.128 W/System.err(10464): at java.lang.reflect.Method.invoke(Native Method)
> 02-13 10:06:51.128 W/System.err(10464): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
> 02-13 10:06:51.128 W/System.err(10464): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:797)

请自行联系软件作者
