### ISSUE TITLE
流量额度单位

### ISSUE THREAD

**Issue by xb0or** [ProxyPanel/ProxyPanel#15]
**功能描述 | Feature request description**
单位MB不太好 建议改成GB或者下拉列表（MB、GB、TB）
![image](https://user-images.githubusercontent.com/57210034/93002588-932dbf80-f527-11ea-9525-c956aedae273.png)

**Comment by ZBrettonYe** [comment]
下拉列表实现起来过于繁琐，改单位也显得无意义
