### ISSUE TITLE
[BUG]流量统计表格显示不正常

### ISSUE THREAD

**Issue by gitject** [ProxyPanel/ProxyPanel#151]
流量使用能正常统计，但是统计表格都显示不正常，包括个人的节点的统计表格都显示不正常

**错误截图**
![image](https://user-images.githubusercontent.com/31369527/106909831-9e35f600-673b-11eb-961f-41659b3ba378.png)

![image](https://user-images.githubusercontent.com/31369527/106909704-8199be00-673b-11eb-9b40-aeb7882d29e5.png)

**信息**
- 面板版本：[例如 Release 2.6.0]

**Comment by ZBrettonYe** [comment]
具体什么不正确法

**Comment by gitject** [comment]
![image](https://user-images.githubusercontent.com/31369527/110067110-f1887c00-7dad-11eb-9b26-b6f411ca4d8d.png)
![image](https://user-images.githubusercontent.com/31369527/110067118-f5b49980-7dad-11eb-8ae7-f501e5a2eda8.png)
![image](https://user-images.githubusercontent.com/31369527/110067126-f9e0b700-7dad-11eb-9ec0-fc674c15e76b.png)
![image](https://user-images.githubusercontent.com/31369527/110067353-88edcf00-7dae-11eb-8227-f86b241c167f.png)

一个在3.1号注册的账号，到现在3.5号，用户列表里显示已经使用1G的流量，流量日志里也有对应的使用节点和流量信息，但是流量统计的的图表都是空的。
节点的流量统计图表也有这情况。

**Comment by ZBrettonYe** [comment]
尝试 #166  的方法

**Comment by gitject** [comment]
手动把memory_limit = 128 改成memory_limit = 256 后在根目录运行 php artisan userDailyTrafficStatistics 解决了，麻烦了
