### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by matthewlu070111** [ProxyPanel/ProxyPanel#152]
在运行代码安装依赖时
composer install --prefer-dist --optimize-autoloader --no-dev
出现以下错误
`In Connection.php line 671:
                                                                                                      
  SQLSTATE[HY000] [2002] Connection timed out (SQL: select * from information_schema.tables where ta  
  ble_schema = www_imxiaoanag_x and table_name = config and table_type = 'BASE TABLE')                
                                                                                                      

In Exception.php line 18:
                                               
  SQLSTATE[HY000] [2002] Connection timed out  
                                               

In PDOConnection.php line 38:
                                               
  SQLSTATE[HY000] [2002] Connection timed out  
                                               

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`

**Comment by maker2002** [comment]
请问你的如何解决这个问题的？我也出现了类似的错误：
`In Connection.php line 671:

  SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'forge' (SQL: select
  * from information_schema.tables where table_schema = forge and table_name = config and table_
  type = 'BASE TABLE')


In Exception.php line 18:

  SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'forge'


In PDOConnection.php line 38:

  SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'forge'
`
