### ISSUE TITLE
节点后台流量统计不增加[BUG]

### ISSUE THREAD

**Issue by cnmars** [ProxyPanel/ProxyPanel#153]
**确保你已经看过 readme和wiki，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**
已看过
**错误描述**

用户使用流量正常

线路上统计节点总用量在增加到一定时间停止增加 如下截图 在第一天使用了20G后就不增加了

**如何复现**
实际操作
**日志**
强烈建议附上在 `域名/admin/logs` 中的报错日志。

**错误截图**
![截屏2021-02-06 下午7.30.05.png](https://i.loli.net/2021/02/06/pPQS8ns9tV7O1C6.png)

**信息**
- 面板版本：[例如 Release 2.6.0]

**额外信息**

**Comment by ZBrettonYe** [comment]
于#151 重复
