### ISSUE TITLE
[BUG]错误的订阅信息

### ISSUE THREAD

**Issue by yuntuvu** [ProxyPanel/ProxyPanel#157]
domain.com/nodeList 以及启用订阅后所获取的Trojan链接均为[固定的10053端口](https://img.vim-cn.com/94/5289faebf0465d72231526930e70b177266e9f.png)，
实际后台配置中[并未设置成10053](https://img.vim-cn.com/bc/6141dd3072a9b498a33046caaa1aedc96d35c6.png)

**Comment by ZBrettonYe** [comment]
对trojan并不熟，麻烦提供正确案例
