### ISSUE TITLE
首页LOGO站内LOGO 

### ISSUE THREAD

**Issue by bickernwong** [ProxyPanel/ProxyPanel#16]
**描述你遇到的bug**
简单的描述一下你遇到的bug
在配置 通用配置 LOGO客服统计 首页LOGO站内LOGO  上传png 图片，点击 提交后没更新
**如何复现你的BUG**
为方便找bug，请说明你bug产生的步骤

**截图**

**Comment by ZBrettonYe** [comment]
要清理浏览器缓存 才会看到
