### ISSUE TITLE
[疑问]Vnet-SSR 单端口模式没有上报

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#161]
Vnet-SSR单端口模式没有上报数据的疑问

1、配置单端口模式，在该模式下没有在线人数，没有流量数据，日志系统->流量使用，也没有任何数据。
2、关闭单端口模式后，在线人数，流量日志都正常显示。

我也不知道哪里的问题，求大佬帮帮忙！

**Comment by kongbaigit** [comment]
一样遇到了该问题 不知道怎么解决
