### ISSUE TITLE
[BUG]速度限制不正常

### ISSUE THREAD

**Issue by gitject** [ProxyPanel/ProxyPanel#163]
**错误描述**
限速设置无法正常限速
面板中的限速是 1 Mbps 的时候，后端上显示的限速是 UserRateLimit=16384000000

**错误截图**

![image](https://user-images.githubusercontent.com/31369527/109833485-43c98000-7c7c-11eb-98cc-6ec7d10e2a45.png)
![image](https://user-images.githubusercontent.com/31369527/109833503-475d0700-7c7c-11eb-8184-d512e179a466.png)

**信息**
- 面板版本：2.6.d

**Comment by ZBrettonYe** [comment]
截图也不愿意给全，只能说单位换算+节点/用户限速，全部取决于服务器后端怎么处理
