### ISSUE TITLE
[BUG]系统流量统计出错

### ISSUE THREAD

**Issue by ThereChave** [ProxyPanel/ProxyPanel#166]
流量统计出错，和 @gitject 反映的一样，类似的节点和用户的小时、日流量均不会统计，在根目录运行php artisan userDailyTrafficStatistics出现如下错误，
`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 8388616 bytes) in /www/wwwroot/xiaochoutu.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 258

In PDOStatement.php line 258:
                                                                                      
  Allowed memory size of 134217728 bytes exhausted (tried to allocate 8388616 bytes)  
`

**信息**
- 面板版本：Release 2.6.0

**额外信息**

**Comment by ZBrettonYe** [comment]
这种PHP报错麻烦 自行谷歌解决

**Comment by ThereChave** [comment]
加到1G仍然不足，之前为128M内存
