### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lovelyou** [ProxyPanel/ProxyPanel#168]
v2ray 订阅节点的端口是服务端口不是 。。。。连接端口

app\Models\Node.php    117行
  'port'        => $this->is_relay ? $this->relay_port : $this->v2_port, 把v2_port改成  port，不然前端是，或者订阅的连接端口就是服务器端口。。。。请大佬核查是不是这样。。。。。。

**Comment by ZBrettonYe** [comment]
对v2ray 不是很熟悉

**Comment by BobCoderS9** [comment]
已解决
