### ISSUE TITLE
[BUG] Server酱 不会定时推送消息。

### ISSUE THREAD

**Issue by GitorNothing** [ProxyPanel/ProxyPanel#171]
面板版本：[在线更新的 2.6]
 
问题： Server酱 不会定时推送消息。

具体表现：在 通用设置 - 通知系统 中，设置好并测试Server酱，能收到测试消息。但自动任务触发的server酱推送，如节点报告，流量异常用户封禁，都收不到消息。这些消息推送在 自动任务 设置中，都已经选择了 server酱。

查看日志，错误显示如下：

![微信图片_20210325164038](https://user-images.githubusercontent.com/19897340/112444568-25413b00-8d89-11eb-89e2-e50f8b3af7aa.png)

之前用2.5.1的时候没有问题，一直都能正常推送。自从升级到2.6后，就失效了。
请问怎样才能解决？
感谢！

**Comment by gitject** [comment]
手动把memory_limit = 128 改成memory_limit = 256 后在根目录运行 php artisan userDailyTrafficStatistics

**Comment by GitorNothing** [comment]
> 手动把memory_limit = 128 改成memory_limit = 256 后在根目录运行 php artisan userDailyTrafficStatistics

修改 BT面板的 PHP配置吗？ 我试试，感谢！

**Comment by NeedforGit** [comment]
> 手动把memory_limit = 128 改成memory_limit = 256 后在根目录运行 php artisan userDailyTrafficStatistics

还不行，已经修改了 PHP 配置 memory_limit = 256，也在根目录运行了 php artisan userDailyTrafficStatistics，还是出现同样的错误。

![微信图片_20210326164859](https://user-images.githubusercontent.com/48271689/112606357-40787d00-8e53-11eb-9164-81701be81259.png)

怎么样才能修复？

**Comment by ZBrettonYe** [comment]
取消 再重选 重新设置
