### ISSUE TITLE
这个MugglePay完全不能用丫

### ISSUE THREAD

**Issue by LInJunYue** [ProxyPanel/ProxyPanel#175]
这个MugglePay完全不能用丫
提示创建订单失败，重置就卡着不动
创建订单错误：array (
'status' => 400,
  'error_code' => 'PAY_PRICE_ERROR',
  'error' => 'Price amount or currency is not set correctly.',
)

**Comment by ZBrettonYe** [comment]
没账号来做测试，加入该支付的时候就说过了
