### ISSUE TITLE
角色权限 已清除提交之后还是管理员。[BUG]

### ISSUE THREAD

**Issue by 110560** [ProxyPanel/ProxyPanel#176]
![IMG_20210503_013744_837](https://user-images.githubusercontent.com/32481672/116822226-39f6c700-abb0-11eb-88d9-9fa02f9b44b0.jpg)
如上图，已清空权限。
![IMG_20210503_013746_682](https://user-images.githubusercontent.com/32481672/116822231-47ac4c80-abb0-11eb-9638-e33458e32473.jpg)
如上图 还是超级管理员

**Comment by 110560** [comment]
演示站已经复现了呀。。。。

**Comment by ZBrettonYe** [comment]
又一个不会看github的家伙
