### ISSUE TITLE
[BUG]工单系统

### ISSUE THREAD

**Issue by cmtomkan310** [ProxyPanel/ProxyPanel#177]
在用户提交工单后，管理员打开工单页面，对该工单进行回复，回复后，弹出【未知错误！请查看日志】

![image](https://user-images.githubusercontent.com/38905231/121470110-457bb000-c9f0-11eb-8d24-af702c9616da.png)

**Comment by ZBrettonYe** [comment]
是时候更新你的代码了

**Comment by cmtomkan310** [comment]
代码已经是最新的了，重新下载了v2.6.0，然后又手动更新了代码
