### ISSUE TITLE
V2RAY ws模式下为什么不能自定义host

### ISSUE THREAD

**Issue by ovenone** [ProxyPanel/ProxyPanel#184]
![image](https://user-images.githubusercontent.com/6820936/123363880-00d24600-d5a6-11eb-815b-61b7fb80c06e.png)
如图片所示    在伪装域名哪里只有选择 不能自定义host  并且这个host不是网站的域名  请问这是需要在哪里添加进列表的吗？   
在tcp+http模式下  没有这个问题 可以自定义

**Comment by aiastia** [comment]
感觉是逻辑问题~

**Comment by RManLuo** [comment]
现在proxypanel的ws模式只能支持TLS，所以必须要在证书授权处添加域名。

**Comment by BobCoderS9** [comment]
已修改，ws模式下非必须添加授权证书域名，但授权证书列表域名仍有效。

**Comment by ovenone** [comment]
感谢大佬    大佬牛逼
