### ISSUE TITLE
[BUG]进入用户管理界面时崩溃

### ISSUE THREAD

**Issue by Huitiank** [ProxyPanel/ProxyPanel#186]
**确保你已经看过 readme和wiki，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**错误描述**
进入用户管理界面时出现错误

**如何复现**
1. 前往用户管理界面

**日志**
[日志链接](https://chicken.huitiank.com/admin/logs?l=eyJpdiI6Ikl5L1ByZ2JoeGZQUWpTdnh0ckZPYWc9PSIsInZhbHVlIjoiUTMwN0xhRnl3Mll6RFBnVEhhMzdZZEgzTE5GNUJVQWh1TWVEaTNjR3BtWT0iLCJtYWMiOiIzMDMyZDZiYzAwNGMwYzJkMDk5MDdkYTNkYTNjNDY4YjY1NDJlYTk4MjgwNzE0ZTRhYTA3YTJhZGUyOTI0MGVkIn0=)

**信息**
- 面板版本：unpanel

**Comment by ZBrettonYe** [comment]
去这里报，https://github.com/BobCoderS9/ProxyPanel

这只管proxypanel的事
