### ISSUE TITLE
建议支持vless协议

### ISSUE THREAD

**Issue by AK47-Plusone** [ProxyPanel/ProxyPanel#191]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述 | Feature request description**
简明扼要地描述需要的功能

**相关资料/额外想法 | Related documents**

**Comment by ZBrettonYe** [comment]
感觉Vless 好像停止开发了，应该是没有支持的必要了
