### ISSUE TITLE
通用设置中添加批量删除选项

### ISSUE THREAD

**Issue by atpdm** [ProxyPanel/ProxyPanel#196]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述 | Feature request description**
通用设置中删除不需要的选项只能单个进行删除.
如果要在国家/地区中删除不需要的选项单个删除速度太慢了.

**相关资料/额外想法 | Related documents**

**Comment by ZBrettonYe** [comment]
@atpdm 实现起来对ui太有挑战了

**Comment by atpdm** [comment]
或许可以换个方式, 缩减通用配置中的一些选项.
比如在国家/地区中的选项, 保留香港/台湾/日本/新加坡/美国等主流地区, 删除比利时,保加利亚等较为冷门的国家/地区.
如果需要这些冷门地区的国家/地区, 再自行添加.

**Comment by ZBrettonYe** [comment]
并不知道为什么要去删除这些东西

**Comment by atpdm** [comment]
是因为在添加节点的时候, 选择地区找起来不方便😂...
