### ISSUE TITLE
[BUG]用户限速无效

### ISSUE THREAD

**Issue by atpdm** [ProxyPanel/ProxyPanel#197]
**确保你已经看过 readme和wiki，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**错误描述**
用户设置限速10m,但是实际使用并不会被限速.

**如何复现**
1. 用户购买套餐(限速10m)
2. 查看用户信息, 确认限速10m
3. 复制该用户订阅进行测速
4. 测速结果未被限速, 会跑满带宽

**日志**
额(⊙﹏⊙),好像并没有关于这个的log

**错误截图**
![image](https://user-images.githubusercontent.com/86911170/128620205-88c4852c-ee5b-4df8-acad-6bea51d30b14.png)
![image](https://user-images.githubusercontent.com/86911170/128620242-3977cd89-0110-4f25-a4f2-260a2a05d683.png)

**信息**
- 面板版本：v2.7.a

**额外信息**
CentOS 7.9.2009
Nginx 1.19.8
MySQL 5.7.34
PHP-7.4
Redis 6.2.5

**Comment by ZBrettonYe** [comment]
一切限速问题和面板无关，直接去看用的后端支不支持用户限速
