### ISSUE TITLE
master版本几处错误

### ISSUE THREAD

**Issue by younk-zhao** [ProxyPanel/ProxyPanel#198]
**错误描述**
错误一:新增线路时，服务端口配置后无法展示在前端页面上，每次修改节点时都会提示服务端口不能为空；

错误二：系统设置里的账号设置Tab页的账号类型选项，无法设置；

错误三：系统里的通知系统Tab页中的最下面四个选项设置成功后无法展示在前端页面上。

**错误截图**
错误一截图：
![image](https://user-images.githubusercontent.com/44158279/129655922-d7ec4055-0db6-4a27-8bd2-c399d572ba6d.png)

错误二截图：
![image](https://user-images.githubusercontent.com/44158279/129656314-0479aeec-d8a3-4f68-8838-e1c2b3296649.png)

错误三截图：
![image](https://user-images.githubusercontent.com/44158279/129656364-f9a20909-01fe-440c-8705-277a031fb30b.png)

**信息**
- 面板版本：[master]

**Comment by BobCoderS9** [comment]
错误一、错误二已修复，错误三检查是正常的
