### ISSUE TITLE
增加节点离线 提醒

### ISSUE THREAD

**Issue by 110560** [ProxyPanel/ProxyPanel#201]
部分节点不能离线 当该节点离线的时候 有个tg推送或者邮箱提醒

编辑节点的页面设置一个是否开启 离线提醒
因为有些节点离线了也不用管它。

**Comment by ZBrettonYe** [comment]
@110560 看不懂 什么和什么？

**Comment by 110560** [comment]
线路管理界面 节点存活时间 有的有时间，有的是离线，
比如A线路和 B线路

我要保证A线路，离线两分钟后， 有TG或者邮箱推送提醒我A线路离线了
B线路则是一直离线状态 这条线路不需要提醒离线 

 所以在编辑节点的页面时 增加一个是否添加 离线推送开关
