### ISSUE TITLE
关于封禁代理的问题！

### ISSUE THREAD

**Issue by cmtomkan310** [ProxyPanel/ProxyPanel#209]
最新面板，Vnet后端
流量达到设定上限后，面板显示封禁代理，但实际用户可继续使用！

![image](https://user-images.githubusercontent.com/38905231/139518603-c5cb76cb-05e2-4b74-84f8-2dccfda485f0.png)

![image](https://user-images.githubusercontent.com/38905231/139518616-b0207a0b-c333-4e5e-a5e4-121b11ec3bc6.png)

这个问题是属于后端还是面板功能的问题？

**Comment by chobitsos** [comment]
后端问题，你每天给后端设置一个crontab自动重启一下就行了，重启之后封禁的用户就上不了了

**Comment by cmtomkan310** [comment]
计划任务没问题，但是如果不下线，24小时内可以跑很多流量啊，但又不能10分钟重启一次。算了换后端吧

**Comment by bingotl** [comment]
同样问题，面板修改用户信息，vnetssr后端也要要重启服务才会生效。废了啊

**Comment by cmtomkan310** [comment]
面板节点管理哪里有一个重载后端，这个能不能深度开发一下，可设置为自动定时重载，经测试，重载可立即生效节点和相关用户的信息更新，同时也不会掉线。

**Comment by ZBrettonYe** [comment]
[8b65f88](https://github.com/ProxyPanel/ProxyPanel/commit/8b65f887de27aed16f8c4b83cfd447aac17db2dd)

这次的更新应该解决了，最初的VNet没有实际封禁用户的问题。

这个应该是VNet没对enable这个字段正确使用。由于我现在没法编译VNet-SSR，只能再面板代码上动手解决了
