### ISSUE TITLE
模仿VnetPanel重构商品

### ISSUE THREAD

**Issue by bickernwong** [ProxyPanel/ProxyPanel#21]
**功能描述 | Feature request description**
建议套餐重构提前到2.5 版本，模仿VnetPanel 数据库重构商品，以便VnetPanel 迁移到ProxyPanel平滑过渡
**相关资料/想法 | Related documents**
VnetPanel 迁移到ProxyPanel会导致订单难以迁移，功能丢失。希望能在VnetPanel 到期前可以迁移到套餐已重构ProxyPanel V2.5

**Comment by ZBrettonYe** [comment]
未来有计划重构商品，
但不会试图兼容vnetpanel
