### ISSUE TITLE
[BUG]Shadowrocket跟默认订阅链接无法下发sni

### ISSUE THREAD

**Issue by SamuelW9527** [ProxyPanel/ProxyPanel#213]
**错误描述**
使用Shadowrocket或者默认的订阅链接均无法下发sni，通过base64解码发现这两个订阅链接均不包含SNI信息

**如何复现**
1. v2rayN使用默认订阅链接时中转节点SNI为空，使用v2rayN专用链接时SNI正确
2. IOS端用shadowrocket添加专用链接，打开节点详情，同上

**信息**
- 面板版本：2.7.a

**Comment by SamuelW9527** [comment]
补充：节点类型为trojan

**Comment by SamuelW9527** [comment]
这个是默认订阅链接 不包含sni
![微信截图_20220314203723](https://user-images.githubusercontent.com/5203050/158174128-b37ba56b-264f-4ed2-acdb-64332b47b581.png)i

这个是自定义客户端v2rayN的链接
![微信截图_20220314204058](https://user-images.githubusercontent.com/5203050/158174238-80648b8c-be79-4141-84b9-92b272c7da6b.png)

**Comment by BobCoderS9** [comment]
@SamuelW9527 我记得通用链接好像是没加
