### ISSUE TITLE
节点名称带有_每日流量报告 发送失败[BUG]

### ISSUE THREAD

**Issue by 110560** [ProxyPanel/ProxyPanel#217]
香港视频_nf_0.8 比如节点名称是这个，就会发生报错
![IMG_20220331_235929_026](https://user-images.githubusercontent.com/32481672/161098901-80c8e061-35f2-4d55-8aee-060d26549992.jpg)
用 md 模式发，如果出现错误字符，才会报 400
TG 提醒  问题可复现。

**Comment by ZBrettonYe** [comment]
小问题，目前不会解决
