### ISSUE TITLE
[BUG] ping api好像已经失效

### ISSUE THREAD

**Issue by yuWorm** [ProxyPanel/ProxyPanel#218]
**确保你已经看过 readme和wiki，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**错误描述**
节点ping的api好像已经失效，访问直接404了

**如何复现**
1:	前往节点管理，进行延迟检测
2：可以直接将api拉出进行访问

**日志**
强烈建议附上在 `域名/admin/logs` 中的报错日志。

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题
![图片](https://user-images.githubusercontent.com/34805071/162374316-096bd2d6-e873-4ee9-8c86-345534e21da4.png)
![图片](https://user-images.githubusercontent.com/34805071/162374596-6841a009-6a6b-41c4-b4cd-214586c90e98.png)

**信息**
- 面板版本：[例如 Release 2.5.1]
Release 2.7.x

**额外信息**

**Comment by ZBrettonYe** [comment]
没好的替代品，暂时就这样
