### ISSUE TITLE
节点基础信息加入节点所属分组

### ISSUE THREAD

**Issue by bickernwong** [ProxyPanel/ProxyPanel#22]
**功能描述 | Feature request description**
节点基础信息加入节点所属分组，方便分类管理
**相关资料/想法 | Related documents**
![group](https://user-images.githubusercontent.com/43773706/94339086-d9a41380-0029-11eb-9918-3921b8e2bd4d.JPG)

**Comment by ZBrettonYe** [comment]
已知问题：
开启这个功能后，用户要是用路由器插件会出现只订阅一组的问题
