### ISSUE TITLE
[BUG] 最新master似乎无法正常安装

### ISSUE THREAD

**Issue by ishkong** [ProxyPanel/ProxyPanel#224]
**确保你已经看过 readme和wiki，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**错误描述**
```bash
In Connection.php line 671:
                                                                                                                                                                
  SQLSTATE[42S02]: Base table or view not found: 1146 Table '数据库名.config' doesn't exist (SQL: insert into `config` (`name`) values (stripe_currency))  
                                                                                                                                                                

In Exception.php line 18:
                                                                                                  
  SQLSTATE[42S02]: Base table or view not found: 1146 Table '数据库名.config' doesn't exist  
                                                                                                  

In PDOConnection.php line 82:
                                                                                                  
  SQLSTATE[42S02]: Base table or view not found: 1146 Table '数据库名.config' doesn't exist  
                                                                                                  
```
**如何复现**
php artisan migrate --seed

**日志**
无

**错误截图**
![image](https://user-images.githubusercontent.com/19740260/173227084-30238df7-1d9d-48d8-b63b-9b0585563508.png)

**信息**
- 面板版本：[3f245ad](https://github.com/ProxyPanel/ProxyPanel/commit/3f245ad7440e645c08a0e3412093c296c9f6628e)

**额外信息**

**Comment by ZBrettonYe** [comment]
你设置的数据库有问题

**Comment by ishkong** [comment]
请问怎么处理呢，回到之前的版本是可以安装的（数据库改动前的那个版本）

------------------------------------------------------------------
***@***.***>
日　期：2022年06月14日 20:18:40
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [ProxyPanel/ProxyPanel] [BUG] 最新master似乎无法正常安装 (Issue #224)

你设置的数据库有问题

**Comment by ZBrettonYe** [comment]
正常更新数据库 php artisan migrate 就够

你 php artisan migrate --seed 什么？

**Comment by ishkong** [comment]
> 正常更新数据库 php artisan migrate 就够
> 
> 你 php artisan migrate --seed 什么？

我直接升级报错，于是我就删了全部重新安装还是报这个错误，这个截图是全部删除完后重新安装报的

**Comment by ZBrettonYe** [comment]
重新删了，包括删数据库？

**Comment by ishkong** [comment]
> 全部删了，包括删数据库？

是的
