### ISSUE TITLE
更新后问题汇报

### ISSUE THREAD

**Issue by cmtomkan310** [ProxyPanel/ProxyPanel#228]
更新后取消了【中转线路】、【端口】自己填写这个功能。却而代之的是中转下拉对话框。
我没整明白怎么用，不知道这个下拉框选择和之前自己填写有什么区别。

1.Vnet
因为我全是gost中转，升级后，导致所有节点中转和端口清空，直接显示IP和单端口。虽说用户更新订阅还可以使用，但不中转部分节点速度受到影响。（只能通过把中转机的ip换成域名，在域名哪里填写中转地址，单端口哪里填写转发端口，才可以正常用）
2.SOGA
soga影响更大，soga后端只能识别PP面板单端口这个字段，不像vnet我可以修改面板单端口为gost转发端口，导致soga后端如果想要gost中转用PP面板就无法使用。

希望老大看到后，尽快解决这个问题，我感觉之前的那种模式挺好的，自由度高。

**Comment by ZBrettonYe** [comment]
改版并没有影响实际功能，只是把中转彻底融进了节点设置里面去了。

> A：不知道这个下拉框选择和之前自己填写有什么区别。
Q：中转节点 自动继承被中转节点的所有代理设置；

> A：导致所有节点中转和端口清空
Q：关于被清空是正常的，我数据库改动没做完善。所有（中转/单）端口都并成 端口，IP域名什么的都一样，只要是中转节点页面还显示的，都是中转节点特有的；

>A：soga影响更大
Q：我记得soga也是用webapi，API方面是零影响的；

**Comment by cmtomkan310** [comment]
已经恢复之前的版本了。不单是这些问题，新建立一个中专节点，比如端口设置1212，保存后。无法修改。还有，一键全部重启vnet的那个命令（php artisan vnet:reload），使用后vnet全部节点无法使用。

老版本如图显示，ip为落地机，单端口为vnet落地机，中转端口和地址均为中专机的。用户订阅后的状态是显示中转地址和端口的，也就是直接连接中转。

新版本取消中转端口和地址。我只能把中转地址解析为域名，在域名哪里填写中转解析域名，而单端口哪里写转发端口12123。这样配置后不可以使用，必须把域名去掉，端口哪里填入实际落地vnet端口443后，可以使用。但这样就没有走中转，而且用户订阅的就是没有中转的状态。然后，还是这个节点，进去编辑，域名哪里填入中转解析域名，单端口哪里填入12123，保存后，神奇的事情发生了，节点可以使用！而且订阅出的结果就是中转地址+中转端口。

比如我有50个vnet节点，都要这样，先删除域名，再换单端口，订阅后使用一下，成功翻墙后，再把域名加上，换中转端口即可。

如果一旦用了php artisan vnet:reload，那么所有vnet节点失效，无法连接。还要从新来过。

今天从早上10点弄到现在，一直有问题，各种测试，刚刚给回退了。

**Comment by cmtomkan310** [comment]
A：不知道这个下拉框选择和之前自己填写有什么区别。
Q：中转节点 自动继承被中转节点的所有代理设置；

按照这个说法，我理解是，新建一个中转，只需要设置ip字段为中转机的ip或者域名，端口设置中转端口就行了。然后我去1号节点，在中转下拉框哪里选择刚才建立的中转节点？

**Comment by cmtomkan310** [comment]
但这种方式有个很大的问题，一台中转机上有可能转发多个节点，那我就要新建多个中转节点，且IP一样，端口不同。

**Comment by cmtomkan310** [comment]
这个bug已经说过了，demo站一样存在。

![image](https://user-images.githubusercontent.com/38905231/177908948-1b3f2de1-4215-436a-9f13-7028815ce33c.png)


![image](https://user-images.githubusercontent.com/38905231/177908912-ac7e4b5f-870a-43fd-9257-02af5becc7af.png)

**Comment by cmtomkan310** [comment]
补充用户页截图
![image](https://user-images.githubusercontent.com/38905231/177909175-bd082a02-6807-4674-a884-ec30de5a626c.png)

**Comment by myannnascar** [comment]
我也是没有搞懂这个逻辑
假如我的中转机地址为 a.com 端口为 10443 ，落地机为 b.com 端口为443
那么应该如何设置节点才能实现将a.com:10443 转发到 b.com:443

**Comment by cmtomkan310** [comment]
如果你现在想这么转发，只能在落地机设置域名为a.com，端口为10443就可以了！前提是不能重启代理服务，不能重新载入，否则失效。失效后你要把落地机的域名删除，端口改回443.就可以了，一定要自己连接上跑一点流量后，再到落地机增加域名为a.com，端口改为10443.


以上是我花了1天功夫，就现有版本测试出的可用中转结论。不知道楼上的看的明白与否？
