### ISSUE TITLE
没有端口的用户购买了套餐后未分配端口

### ISSUE THREAD

**Issue by bickernwong** [ProxyPanel/ProxyPanel#23]
**描述你遇到的bug**
简单的描述一下你遇到的bug
我设置了被封禁和过期一个月的用户端口自动释放，没有端口的用户购买了套餐后未分配端口。
**如何复现你的BUG**
为方便找bug，请说明你bug产生的步骤

**截图**

**Comment by ZBrettonYe** [comment]
- [ ]
