### ISSUE TITLE
[BUG] 线路管理无法正确传导Trojan和V2ray的节点数据 

### ISSUE THREAD

**Issue by Ivaneus** [ProxyPanel/ProxyPanel#230]
**确保你已经看过 readme和wiki，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**错误描述**
当对新增V2RAY节点时，所填写的加密方式和端口两个字段无法被后端读取到，而且二次编辑节点信息的时候，加密方式无法选中任何项目，需要切换到ss或者其他再切换回来才能选择。
同理，Trojan节点类型同样存在上述问题

**如何复现**
1. 前往线路管理页面，新增一个V2RAY类型的节点
2. 观察XRAYR后端数据
3. 二次编辑V2RAY类型节点

**日志**
XRAYR日志
Parse node info failed: {"id":1,"is_udp":false,"speed_limit":125000000,"client_limit":1000,"push_port":1080,"redirect_url":"","secret":"u3H1xGhD","key":"","pem":"","v2_license":"","v2_alter_id":"16","v2_port":null,"v2_method":"","v2_net":"ws","v2_type":"none","v2_host":"","v2_path":"\/okbuxvdak6aq0oev","v2_tls":false,"v2_tls_provider":null},
Panel Log
![image](https://user-images.githubusercontent.com/28734491/180373936-045eced4-5398-4006-8276-d7467c2c7de6.png)
**错误截图**
![image](https://user-images.githubusercontent.com/28734491/180374065-c8f796a0-ad8a-4125-833e-b1beb3f06b40.png)

**信息**
- 面板版本：latest

**额外信息**

**Comment by ZBrettonYe** [comment]
是否可以在demo中复现
