### ISSUE TITLE
关于回滚的请求

### ISSUE THREAD

**Issue by cmtomkan310** [ProxyPanel/ProxyPanel#232]
回滚后并没有解决之前的问题，中转这个选项很鸡肋，我不知道开发者到底用不用中转，还是之前的那种模式简单，在节点配页面，有中转地址+中转端口。订阅可以订阅出中转地址，重载还是按照IP重载，都很完美。无非就是差一个批量重载，在原有基础上加上批量重载，就非常完美了。

中转是在中转机上开隧道连接到节点。我不知道这个开发者明不明白？
大部分中转都是国内机器，国内机器根本不让安装代理，所以大家会使用隧道模式，那PP面板上这个中转，到底是什么意思？是建立中转机？还是什么意思？我研究了很久，还是没整明白！

现在如果取消节点配置页面的中转地址和中转端口，那但凡需要做中转的，都无法再使用这个面板，而且现在有多少人是用直连？所以我觉得开发者应该多听听用户的建议，尤其是使用PP面板的大机场主。

其实新版本出后我总会用测试系统升级新版，发现问题已经提了，开发者说修改，但测试后发现修改仅限于中转端口能保存了。
https://github.com/ProxyPanel/ProxyPanel/issues/228

我之前从ssrpanel到vnetpanel再到pp，一路用下来，目前PP我认为算是比较好用的了，起码比sspanel更容易上手，配置也不会更繁琐。希望开发者能明白我们的诉求。

**Comment by Ivaneus** [comment]
我也觉得旧版中转更加实用
按照现在新版中转，其实是被定义成一个新的节点配置策略。
从前是节点include中转功能 现在是分成了直连节点+中转节点两种节点类型，并且中转节点必须依赖一个直连节点。
也就是说如今要建立中转节点，就必须创建 1个直连节点+1个中转节点，而实际上，原来的旧版，只需要创建一个节点即可，中转则是作为一个附加的可选功能。
这样一来，能够为纯中转节点的机场节约大部分的升级工作量不是么
