### ISSUE TITLE
[BUG]生成卡券类型为充值券时 'priority' cannot be null 

### ISSUE THREAD

**Issue by isyekong** [ProxyPanel/ProxyPanel#235]
**错误描述**
生成卡券时，类型为 充值券，会出现sql语法错误

**如何复现**
生成卡券，选择类型为 充值券，会出现sql语法错误

**日志**
`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'priority' cannot be null (SQL: insert into `coupon` (`name`, `type`, `priority`, `usable_times`, `value`, `start_time`, `end_time`, `limit`, `logo`, `status`, `sn`, `updated_at`, `created_at`) values (test, 3, ?, 1, 99, 1663776000, 1666368000, {"used":"1"}, ?, 0, Ilz0Bj2h, 2022-09-22 20:00:24, 2022-09-22 20:00:24))
`

**错误截图**
![image](https://user-images.githubusercontent.com/20068143/191741731-c03bf1e9-be46-4f93-ada8-6cc8bdde9cc0.png)

**信息**
- 面板版本： 2.7.1

**额外信息**

**Comment by ZBrettonYe** [comment]
用的数据库是啥版本哦，明明数据库预设默认值就有0的，为什么到你手里就有 null 的报错了

**Comment by isyekong** [comment]
> 用的数据库是啥版本哦，明明数据库预设默认值就有0的，为什么到你手里就有 null 的报错了

您好，是MySQL 5.7.39
