### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gitject** [ProxyPanel/ProxyPanel#236]
**错误描述**
修改“系统设置”内的设置，部分设置及时生效
但部分设置需要ssh回到网站文件夹里输入
“php artisan optimize”才生效

**日志**
日志报错出现整个提示
![image](https://user-images.githubusercontent.com/31369527/192146941-79d8c542-ef7a-4f72-a3ea-58223f3c127c.png)

**信息**
- 面板版本： 
最新的Master（d30a86c）

**额外信息**

**Comment by ZBrettonYe** [comment]
你网站权限没配置好，这报错都出来了
