### ISSUE TITLE
PushDear 不会设置

### ISSUE THREAD

**Issue by gitject** [ProxyPanel/ProxyPanel#237]
**错误描述**
PushDear的推送方式，在设置页面，测试发送是正常能发送的。
但是在定时任务出现如图的报错。
“The pushkey must be a string.”

**错误截图**
![image](https://user-images.githubusercontent.com/31369527/193386617-7b774462-6c67-40d1-bae0-b72932919920.png)

**信息**
- 面板版本：最新的master,    a10c3d3

**Comment by ZBrettonYe** [comment]
你pushkey设了啥哦，’The pushkey must be a string‘ 自己去有道翻译 都知道报错内容的。

**Comment by gitject** [comment]
我知道是提示是类型问题，但是测试发送都能正常发送接收，但在日常任务就报错了。
生成的是一串PDU开头的PushDeer Key，不是pushkey，是这个问题吗？

通过官方URL 发送没问题，且点击面板的“发送测试信息”，终端也能正常收到提示。但是在日常任务就类型报错，
![image](https://user-images.githubusercontent.com/31369527/195270431-4c36bf00-c1f3-4d7e-8770-cb1fbb5a63e4.png)
![image](https://user-images.githubusercontent.com/31369527/195271290-db33c6d7-a4f0-4110-b2e4-5186ffbaf96d.png)
![image](https://user-images.githubusercontent.com/31369527/195270793-aebedb2c-9596-47b3-9b89-7aa72529f159.png)

**Comment by gitject** [comment]
重启服务器后自动解决了....
