### ISSUE TITLE
[BUG] 修改env，其他项能正常修改，只有修改发件信息无法生效

### ISSUE THREAD

**Issue by gitject** [ProxyPanel/ProxyPanel#239]
**确保你已经看过 readme和wiki，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**错误描述**
 修改env，只有修改发件信息无法生效

修改该env里的APP_ENV，APP_DEBUG，数据库信息都能正常生效，但是修改发件信息无论改什么都是用 "admin@proxypanel.ml"发出然后报错。

修改完env有更新缓存
php artisan optimize

![image](https://user-images.githubusercontent.com/31369527/195130763-fe895dcf-bc9f-47fd-a2b0-ba8032bc4669.png)

**信息**
- 面板版本：[最新版master]

**Comment by ZBrettonYe** [comment]
无法复现，试试重启服务器吧
