### ISSUE TITLE
易支付接口对接地址问题

### ISSUE THREAD

**Issue by bickernwong** [ProxyPanel/ProxyPanel#24]
**描述你遇到的bug**
简单的描述一下你遇到的bug

ProxyPanel自帶SDK

1.找到支付系统->易支付

2.支付URL填寫：https://api.paytaro.com/submit.php

支付收款二维码地址多了个“submit.php” 估计是Bug，自动添加了一个，造成地址错误，弹不出收款二维码  https://api.paytaro.com/submit.phpsubmit.php?pid=21170&type=alipay&notify_url=https%3A%2F%2Ffreegecko.com%2Fcallback%2Fnotify%3Fmethod%3Depay&return_url=https%3A%2F%2Ffreegecko.com%2Finvoices&out_trade_no=vmMlXA79&name=Geckoiplc&money=20&sign_type=MD5&sign=f838d9fa9d0eaa1c1995fa1233373132

支付URL改寫：https://api.paytaro.com/
支付成功但支付回调失败，通知地址 https://XXXXXXX.com/callback/notify?method=epay
未知支付：alipay
异常来源：Symfony\Component\Debug\Exception\FatalThrowableError
Call to a member function notify() on bool {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function notify() on bool at /www/wwwroot/XXXXXXX.com/proxypanel/app/Http/Controllers/PaymentController.php:38)
**如何复现你的BUG**
为方便找bug，请说明你bug产生的步骤

**截图**

**Comment by ZBrettonYe** [comment]
![image](https://user-images.githubusercontent.com/18015854/94396477-95815200-0194-11eb-96b9-bc00c5ee6da7.png)
