### ISSUE TITLE
[BUG] 开启第三方登录后，可绕过邀请注册的机制

### ISSUE THREAD

**Issue by isyekong** [ProxyPanel/ProxyPanel#243]
**错误描述**
开启第三方登录后，可绕过邀请注册的机制

**如何复现**
1. 后台开启第三方登录，如Google
2. 注册界面点击底部的快速注册
3. 无需验证邮箱、无需邀请码注册

**信息**
- 面板版本：2.7.1

**Comment by ZBrettonYe** [comment]
无需验证邮箱这一点是符合逻辑的，第三方APP的邮箱是验证过的。BUG在邀请码上面。现在就禁掉了开启强制邀请码时的通过第三方注册。
