### ISSUE TITLE
[BUG] 宝塔部署的情况下，不设置SSL无法登录后台，以及按照WIKI部署之后节点的API地址无法访问·

### ISSUE THREAD

**Issue by Ivaneus** [ProxyPanel/ProxyPanel#245]
**确保你已经看过 readme和wiki，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**错误描述**
宝塔部署的情况下，不设置SSL无法登录后台，设置ssl之后才能登陆

按照WIKI部署之后节点的API地址无法访问，例如我设置了一个节点，然后对应api地址应该是
https://xxxxx/api/trojan/v1/node/1
demo中访问该地址返回
{"status":"fail","code":400,"data":null,"message":"Your key is null!"}

但是我宝塔构建出来的却直接返回
 
哎呦！
错❌误携带了报告：
找不到网页

确定节点信息正确建立，并且尝试回退部署旧commit的proxypanel不会遇到这样的问题，是新版中部署缺少某个环节？

**Comment by ZBrettonYe** [comment]
SSL无法登录后台 是你开启了强SSL 模式，env里可以关。
不是域名用错了 就是没设置好。 和宝塔没关系 

都是你设置问题，慢慢摸索
