### ISSUE TITLE
[BUG]在网站目录 运行php artisan route:list命令报错

### ISSUE THREAD

**Issue by Ivaneus** [ProxyPanel/ProxyPanel#246]
**确保你已经看过 readme和wiki，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**错误描述**
在网站目录 运行php artisan route:list命令报错
无法通过route:list罗列完整路由
报错跟paypal相关的支付网关信息
怀疑跟最近重构支付api的更新有关

**如何复现**
在网站目录 运行php artisan route:list

**日志**
 php artisan route:list

In Container.php line 811:
                                                                      
  Target class [App\Http\Controllers\Gateway\PayPal] does not exist.  
                                                                      

In Container.php line 809:
                                                            
  Class App\Http\Controllers\Gateway\PayPal does not exist  
                                                            

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
- 面板版本：master分支

**额外信息**

**Comment by ZBrettonYe** [comment]
最新代码不可能存在这个问题，Controllers\Gateway\PayPal 这个都不存在这个目录下了

**Comment by Ivaneus** [comment]
我也发现了， 这个目录应该不存在了，但是composer下载的的插件中仍然在使用这些目录

**Comment by Ivaneus** [comment]
我通过更换PHP版本，重装宝塔面板都试过，依旧如此报错，不知道这些报错会不会影响支付设置
