### ISSUE TITLE
新安装的Master版本无法进入系统设置[BUG]

### ISSUE THREAD

**Issue by Geek-lkj** [ProxyPanel/ProxyPanel#247]
**确保你已经看过 readme和wiki，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**错误描述**
对错误的清晰简洁描述

**如何复现**
1. 前往XXX页面
2. ...

**日志**
Undefined index: (View: /www/wwwroot/dasa.com/resources/views/admin/config/system.blade.php) {"userId":1,"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): Undefined index: (View: /www/wwwroot/dasa.com/resources/views/admin/config/system.blade.php) at /www/wwwroot/dasa.com/resources/views/admin/config/system.blade.php:164)

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
- 面板版本：[例如 Release 2.5.1]

**额外信息**

**Comment by Geek-lkj** [comment]
新安装后其他页面都能访问，就设置->系统设置点进去就报错

**Comment by Geek-lkj** [comment]
同时 在根目录执行
php artisan optimize

会报错
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /www/wwwroot/dasa.com/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 65 and defined in /www/wwwroot/dasa.com/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:120
Stack trace:
#0 /www/wwwroot/dasa.com/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(65): Illuminate\Routing\UrlGenerator->__construct(Object(Illuminate\Routing\RouteCollection), NULL, NULL)
#1 /www/wwwroot/dasa.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}(Object(Illuminate\Foundation\Application), Array)

**Comment by ZBrettonYe** [comment]
你数据库里 standard_currency 这个值是啥？
