### ISSUE TITLE
用户视角不能显示 知 识 库

### ISSUE THREAD

**Issue by freegecko** [ProxyPanel/ProxyPanel#248]
用户登录后点击“帮助”不能显示 知 识 库，必须选择语言才能显示 知 识 库

**Comment by ZBrettonYe** [comment]
你.env文件中的语言选项一定不在支持的语言里，所以才不会默认显示

**Comment by freegecko** [comment]
这个坑是用https://demo.proxypanel.cf/ 测试出来的

**Comment by ZBrettonYe** [comment]
一样的原因，demo已经改了
