### ISSUE TITLE
[BUG]添加后端提示找不到页面

### ISSUE THREAD

**Issue by 192255** [ProxyPanel/ProxyPanel#249]
**确保你已经看过 readme和wiki，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**错误描述**
对错误的清晰简洁描述

**如何复现**
1. 前往XXX页面
线路授权node1节点v2ray秘钥添加到v2rayR后端，启动后端时提示
 <h3>错❌误携带了报告：</h3>
xrayr_1  |             <code class="error-advise">找不到网页</code>

**日志**
强烈建议附上在 `域名/admin/logs` 中的报错日志。
[2023-01-22 00:00:00] local.WARNING: 异常请求：http://127.0.0.1/api/v2ray/v1/node/1，IP：127.0.0.1  
[2023-01-22 00:00:00] local.ERROR: 来源：http://127.0.0.1/api/v2ray/v1/node/1
访问者IP：127.0.0.1Symfony\Component\HttpKernel\Exception\NotFoundHttpException  

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
- 面板版本：[例如 Release 2.7]

**额外信息**

**Comment by 192255** [comment]
版本master:2.7.a，新手入坑

**Comment by 192255** [comment]
经测试最新版本master git clone下来的版本存在该现象

**Comment by ZBrettonYe** [comment]
并不存在的哈，确认一下直接的节点是不是ID为1，还有授权/后端访问域名是否一致

**Comment by 192255** [comment]
节点是ID为1没错，因为后端跟面板装在同一台，所以直接用127访问
