### ISSUE TITLE
数据库user表复制一条用户数据前台用户列表报错

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#25]
**描述你遇到的bug**
从数据库的user表，复制一条账号数据，前台点击会员列表报“访问被拒绝”

**如何复现你的BUG**
1、user表，2复制数据，3访问/admin/userList，报错
**截图**
![image](https://user-images.githubusercontent.com/63467104/94180116-16f48e00-fed0-11ea-85e8-e21c959c97d7.png)

![image](https://user-images.githubusercontent.com/63467104/94180085-0b08cc00-fed0-11ea-825d-f69cb33b0f85.png)

**Comment by ZBrettonYe** [comment]
用户表 和 订阅表是联动的
