### ISSUE TITLE
composer update error

### ISSUE THREAD

**Issue by ehsan0github** [ProxyPanel/ProxyPanel#251]
when I execute this command:
composer install --prefer-dist --optimize-autoloader --no-dev
I see this error and I don't know what is the root of this problem
![Screenshot 2023-01-28 195015](https://user-images.githubusercontent.com/123427867/215277383-3529ade7-6424-43c8-9dd1-c62eb2da0d50.jpg)
@ZBrettonYe

**Comment by ehsan0github** [comment]
I reinstall everything but this time I have trouble in DB
![Screenshot 2023-01-29 032326](https://user-images.githubusercontent.com/123427867/215296577-d7d1837a-6f91-4941-a1fc-1cde0587cffb.jpg)
I wish you can help me

**Comment by ehsan0github** [comment]
after run this command 
sudo apt-get install php7.4-mysql
![Screenshot 2023-01-29 033807](https://user-images.githubusercontent.com/123427867/215296862-ecdd23bf-13c7-4e75-bc02-aa6ccb602fa0.jpg)
help me

**Comment by ZBrettonYe** [comment]
did u really speak English？ everything is in English. And it already told u where is the problem.
