### ISSUE TITLE
[BUG]前台推广显示失效

### ISSUE THREAD

**Issue by cmtomkan310** [ProxyPanel/ProxyPanel#252]
系统设置开启推广后，前台web页无法显示，demo站已复现。
![image](https://user-images.githubusercontent.com/38905231/215301892-d8be1a2e-e021-48c5-8dfd-8c2869121846.png)
![image](https://user-images.githubusercontent.com/38905231/215301907-88c0b060-fcdf-441b-8412-588438ab1b0f.png)

**Comment by ZBrettonYe** [comment]
推广先决条件是帐号有有效套餐

**Comment by cmtomkan310** [comment]
后台图1设置后，前台推广点开500错误。图1如果为空，推广可以正常打开。已复现

![image](https://user-images.githubusercontent.com/38905231/215312420-d665f42c-ef60-4fa7-bb2e-2352c6be475e.png)

![image](https://user-images.githubusercontent.com/38905231/215312436-4332be8f-8af8-46ec-b5a0-d11a640504ba.png)
