### ISSUE TITLE
[BUG]用户分组

### ISSUE THREAD

**Issue by cmtomkan310** [ProxyPanel/ProxyPanel#256]
按照分组定义
用户分组控制（同一节点可分配至多个分组，一个用户只能属于一个分组；对于用户可见/可用节点：先按分组后按等级）

实测：节点1号2号3号   分别对应等级VIP1、2、3

用户A等级1（无分组） 看到1号节点，订阅后只显示1节点【无问题】
用户B等级1（有分组，组别里面有2号3号节点），订阅后只显示1节点【有问题】
按照分组定义应该是优先分组再按等级，用户B应该显示1-3号节点

**Comment by ZBrettonYe** [comment]
这里的优先不是合并，而是过滤。 用户B 应该看不到任何节点
