### ISSUE TITLE
[BUG] No translation available for account info.

### ISSUE THREAD

**Issue by Mohsen7s** [ProxyPanel/ProxyPanel#258]
Subscription Message : 剩余流量：100GB, 过期时间：2023-04-20
Subscription info on clients is chinese only because it's hardcoded in following file.

[https://github.com/ProxyPanel/ProxyPanel/blob/795a7420c6022a322637f48e95cd79d18d64a56e/app/Helpers/ClientConfig.php#L242](https://github.com/ProxyPanel/ProxyPanel/blob/795a7420c6022a322637f48e95cd79d18d64a56e/app/Helpers/ClientConfig.php#L242)

Please add a translate value for that.

**Comment by ZBrettonYe** [comment]
done
