### ISSUE TITLE
隐藏节点订阅地址

### ISSUE THREAD

**Issue by bickernwong** [ProxyPanel/ProxyPanel#26]
**功能描述 | Feature request description**
为防止恶意举报，订阅地址DNS投毒，建议隐藏节点订阅地址，只让付费用户可见。
**相关资料/想法 | Related documents**

**Comment by ZBrettonYe** [comment]
那免费用户试用的时候怎么订阅呢？

既然已经支持订阅链接已经和网站面板链接可以分开，为什么要订阅投毒不连面板一起投毒？

这个功能，这样看起来就有点鸡肋
