### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yangliu123** [ProxyPanel/ProxyPanel#260]
**确保你已经看过 readme和wiki，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**错误描述**
clash订阅链接下载的时候不支持mac订阅

**如何复现**
1. 复制订阅链接的时候导入时候会报错

**日志**
强烈建议附上在 `域名/admin/logs` 中的报错日志。

**错误截图**
![图片](https://user-images.githubusercontent.com/10783503/228491324-2e62b06f-43a5-478b-a7d8-6215746ec8d4.png)

**信息**
- 面板版本：[例如 Release 2.7.0]

**额外信息**
1.订阅链接下载解析的yaml文件加上单引号
错误的图：
![图片](https://user-images.githubusercontent.com/10783503/228491564-c9075730-f54a-4231-8570-47d9e8dd919b.png)
正确的图：
![图片](https://user-images.githubusercontent.com/10783503/228491645-c7b543aa-aabd-4e96-9e14-1b54a45ac019.png)

**Comment by ZBrettonYe** [comment]
: 在哪里

**Comment by liujianwei1988** [comment]
和单引号确实没有关系，但是windows下面的clash订阅可以正确识别yaml文件，但是到了mac和安卓手机就没有办法识别了,苹果报错行数在windows的clash最后一行。

**Comment by liujianwei1988** [comment]
用的是默认的模板的。

**Comment by liujianwei1988** [comment]
但是，很神奇的问题，windows电脑下载后的模板直接导入到手机和mac电脑中，就可以正常使用，我尝试修改了Yum::dump格式化之后，依然不能解决这个问题。

**Comment by ZBrettonYe** [comment]
安装提示，和’ 没任何关系，提示是多了一个冒号
