### ISSUE TITLE
请求修复一下ClashX 和ClashR客户端订阅

### ISSUE THREAD

**Issue by liujianwei1988** [ProxyPanel/ProxyPanel#264]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述 | Feature request description**
简明扼要地描述需要的功能

**相关资料/额外想法 | Related documents**

**Comment by ZBrettonYe** [comment]
无任何内容，不理会
