### ISSUE TITLE
[BUG]无法监控用户流量和用户状态

### ISSUE THREAD

**Issue by onjacky** [ProxyPanel/ProxyPanel#268]
前后端都搭建好了，但是复制首页的阅读订阅连接，将订阅导入客户端。
可以正常连接，也可以上网。
但是不论怎么使用，后台的流量也不会减少。
用户状态也不更新。
节点的流量也不统计，节点在线也一直是0

**Comment by onjacky** [comment]
能不能给个国内的联系方式，有些问题可以付费解决，谢谢

**Comment by onjacky** [comment]
如果可以的话麻烦 加一下QQ77790079

**Comment by ZBrettonYe** [comment]
检查你面板的自动化任务有没有在后台跑起来

**Comment by onjacky** [comment]
您好：
     您的来信我定将详细阅读。但由于本人时间与精力有限，回信的先后次序为“客户、亲人、同事、朋友、陌生人”。如果为您带来不便还请谅解。
