### ISSUE TITLE
填写PushBear订阅二维码导致前台无法访问

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#27]
**描述你遇到的bug**
1、填写PushBear订阅二维码，前台会员登录提示“访问被拒绝（图2）”
2、删除地址则正常访问
3、日志报错记录（图3）

**如何复现你的BUG**
1、管理员账号登录后台；
2、开启PushBear，并填写订阅二维码地址，前台随意注册账号都无法正常登录；

**截图**
![image](https://user-images.githubusercontent.com/63467104/94430961-46a0e000-01c7-11eb-8633-31ee82733893.png)
![image](https://user-images.githubusercontent.com/63467104/94431282-a6978680-01c7-11eb-8f6b-6df313d2358b.png)
![image](https://user-images.githubusercontent.com/63467104/94431453-e52d4100-01c7-11eb-8211-e5d0dabaac78.png)

**Comment by ZBrettonYe** [comment]
这个是 simplesoftwareio/simple-qrcode 组件包造成的

有和组件包作者反馈过，并没有什么好的回复
