### ISSUE TITLE
Advanced Statistics

### ISSUE THREAD

**Issue by GrigorGB** [ProxyPanel/ProxyPanel#270]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述 | Feature request description**
简明扼要地描述需要的功能

It would be great to have the following statistics available on the panel, as the data is somehow already being logged and saved in the DB:
1. Ability to see each server's traffic usage per hour, per day, per month
2. Ability to see the users currently online on a specific server directly from the server page
3. Ability to see each user's traffic usage per hour, per day, per month
4. Ability to see each user's traffic per server (per hour, per day, per month)

**相关资料/额外想法 | Related documents**
Those features are partially implemented on Shadowsocks manager, V2Board, SSPanel

**Comment by ZBrettonYe** [comment]
all of those requests are already in Logs 😓

**Comment by GrigorGB** [comment]
indeed, all those logs are stored in the DB, my suggestion (which is just a suggestion, it is up to you to take it into consideration or not) is to bring them to the web interface for better reports.

**Comment by ZBrettonYe** [comment]
My ans is there are already in the "web interface" under admin dashboard Logs' session > indeed, all those logs are stored in the DB, my suggestion (which is just a suggestion, it is up to you to take it into consideration or not) is to bring them to the web interface for better reports.
