### ISSUE TITLE
[BUG] clash 配置托管失败

### ISSUE THREAD

**Issue by 110560** [ProxyPanel/ProxyPanel#273]
复制后用 clashX最新版本 添加托管配置提示 配置不合法    ， clash  Windows客户端  也无法应用配置 ，是需要更新一下面板了吗？演示站已复现问题

![IMG_20230530_111927_441](https://github.com/ProxyPanel/ProxyPanel/assets/32481672/ff57ce96-005d-49be-b1da-4fd9c7c831e1)
![IMG_20230530_111932_550](https://github.com/ProxyPanel/ProxyPanel/assets/32481672/9306c872-2b62-4629-86cb-d276c0a4706f)

**Comment by oysterooo** [comment]
同样有这个问题

**Comment by 110560** [comment]
macos clashX 最新版本 添加托管配置提示 配置不合法

**Comment by 110560** [comment]
clash Windows客户端 正常

macos clashx 客户端  托管配置  提示 配置不合法
2.8.X版本

**Comment by 110560** [comment]
macos clashx 客户端 url 请从mac上复制 本机PC a 复制 远程粘贴b macos pc 就配置不合法
