### ISSUE TITLE
[BUG]当用户的访问IP为IPV6时 网站后台无法正常识别

### ISSUE THREAD

**Issue by Misaka18680** [ProxyPanel/ProxyPanel#275]
**确保你已经看过 readme和wiki，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**错误描述**
[BUG]当用户的访问IP为IPV6时 网站后台无法正常识别用户IP来源并返回
哎呦！
错?误携带了报告：
检测到未知IP或使用代理访问，禁止访问
后端日志为
local   错误  11:20:05  [IPSB] 解析[IP地址]错误: 'cURL error 77: error setting certificate verify locations:  
2  local   Notice  11:20:05  识别到IPv6，尝试解析：[IP地址]
**如何复现**
1. 用支持IPV6且IPV6优先的设备/代理打开搭建好的proxypanel网站

**日志**
后端日志为
local   错误  11:20:05  [IPSB] 解析[IP地址]错误: 'cURL error 77: error setting certificate verify locations:  
2  local   Notice  11:20:05  识别到IPv6，尝试解析：[IP地址]

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
- 面板版本：[例如 Release 2.5.1]
2.8.0
**额外信息**

**Comment by ZBrettonYe** [comment]
该问题不再适用于3.0.0版本
