### ISSUE TITLE
[BUG] 订单支付可重复

### ISSUE THREAD

**Issue by 110560** [ProxyPanel/ProxyPanel#277]
点击支付后 网络如果不好 网页提示正在加载 返回支付界面 再点支付 继续提示正在加载  最后支付成功后 就会有多个订单 支付完成

**Comment by ZBrettonYe** [comment]
基本是网络卡了才会出现这种情况吧。

**Comment by 110560** [comment]
是的，  微信支付宝网络卡的也不会多收款呀

**Comment by ZBrettonYe** [comment]
你服务器有腾讯云和阿里云怎么多，就可以不卡了。

**Comment by 110560** [comment]
加一个订单判断 
那些订单最后的秒数都一样的 
比如 卡住的时候创建的订单 时间都是 
2023-08-13 17:07:03
