### ISSUE TITLE
[BUG]偶尔打开网站提示未知IP，发现演示站也出现同样的问题

### ISSUE THREAD

**Issue by MrShellad** [ProxyPanel/ProxyPanel#279]
[BUG]偶尔打开网站提示未知IP，发现演示站也出现同样的问题
版本是3.0.a
控制台显示403
网站目录已经给了完整的权限，依然无法解决，重新安装，新的数据库也无法打开

https://proxypanel.ddo.jp/ 
可以复现

**Comment by ZBrettonYe** [comment]
fixed
