### ISSUE TITLE
中转端口自动变更10053[BUG]

### ISSUE THREAD

**Issue by wxkeykey** [ProxyPanel/ProxyPanel#283]
**确保你已经看过 readme和wiki，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**错误描述**
对错误的清晰简洁描述
中转端口修改完成,保存重新打开,端口自动变成10053
**如何复现**
官方 demo 也是一样的

**日志**
强烈建议附上在 `域名/admin/logs` 中的报错日志。

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题
![image](https://github.com/ProxyPanel/ProxyPanel/assets/61955165/0da45f38-ee6c-489e-a978-3439f5915bae)

**信息**
- 面板版本：[例如 Release 2.5.1]
面板3.0.a
**额外信息**
<div class="form-group row">
                                            <label for="v2_port" class="col-md-3 col-form-label">{{ trans('model.node.service_port') }}</label>
                                            <input type="number" class="form-control col-md-4" name="port" id="v2_port" value="10053" hidden/>
                                        </div>
不知道 怎么修改,改10054 中转端口会自动变成10054

**Comment by wxkeykey** [comment]
<div class="form-group row">
                                                <label for="v2_port" class="col-md-3 col-form-label">{{ trans('model.node.service_port') }}</label>
                                                <input type="number" class="form-control col-md-4" name="port" id="v2_port" value="10053" hidden/>
                                            </div>

不知道 怎么修改,改10054 中转端口会自动变成10054

**Comment by ZBrettonYe** [comment]
无法复现

**Comment by Nkurai** [comment]
我也遇到了同样问题
