### ISSUE TITLE
[BUG]用户流量耗尽后，订阅返回错误

### ISSUE THREAD

**Issue by 110560** [ProxyPanel/ProxyPanel#289]
V2.8订阅 返回的是 流量耗尽，请重新购买或重置流量
V3.0返回的是
HTTP/1.0 200 OK Cache-Control: no-cache, private Date: Wed, 16 Oct 2024 02:26:43 GMT dm1lc3M6Ly9ld29nSUNBZ0luWWlPaUFpTWlJc0NpQWdJQ0FpY0hNaU9pQWlYSFUyWkRReFhIVTVNV05tWEhVNE1ERTNYSFUxWXpOa1hIVm1aakJqWEhVNFltWTNYSFU1TVdOa1hIVTJOV0l3WEhVNFpESmtYSFUwWlRjd1hIVTJNakUyWEhVNU1XTmtYSFUzWmpabFhIVTJaRFF4WEhVNU1XTm1YSFZtWmpBeElpd0tJQ0FnSUNKaFpHUWlPaUFpYUhSMGNITTZYQzljTDNCeWIzaDVjR0Z1Wld3dVpHUnZMbXB3SWl3S0lDQWdJQ0p3YjNKMElqb2dNQ3dLSUNBZ0lDSnBaQ0k2SURBc0NpQWdJQ0FpWVdsa0lqb2dNQ3dLSUNBZ0lDSnVaWFFpT2lBaWRHTndJaXdLSUNBZ0lDSjBlWEJsSWpvZ0ltNXZibVVpTEFvZ0lDQWdJbWh2YzNRaU9pQWlhSFIwY0hNNlhDOWNMM0J5YjNoNWNHRnVaV3d1WkdSdkxtcHdJaXdLSUNBZ0lDSndZWFJvSWpvZ0lsd3ZJaXdLSUNBZ0lDSjBiSE1pT2lBaWRHeHpJZ3A5Cg
解码后
演示站测试
{
    "v": "2",
    "ps": "\u6d41\u91cf\u8017\u5c3d\uff0c\u8bf7\u91cd\u65b0\u8d2d\u4e70\u6216\u91cd\u7f6e\u6d41\u91cf\uff01",
    "add": "https:\/\/proxypane****",
    "port": 0,
    "id": 0,
    "aid": 0,
    "net": "tcp",
    "type": "none",
    "host": "https:\/\/proxypanel***",
    "path": "\/",
    "tls": "tls"
}

**Comment by 110560** [comment]
改为和原来一样 订阅后返回流量耗尽，请重新购买或重置流量

**Comment by 110560** [comment]
以为更新了解决了  演示站试了一下  还是不显示的 老大你自己试试  
v2rayn都显示不对
![image](https://github.com/user-attachments/assets/afffdb98-84d6-4ac6-a234-97c8ef72f171)
ssr客户端也是不行。。。改好了我再测试

**Comment by ZBrettonYe** [comment]
演示站代码不一定是最新的

**Comment by 110560** [comment]
> 演示站代码不一定是最新的

那可否 从新发布一下V3.0内的代码吧  挺重要的提示

还有一个bug 
用户当前有使用中的套餐   预支付套餐  取消预支付套餐后 到期时间正确减了   但是可用流量也扣为0了
加个判定条件  当前有使用中的套餐  有可用流量 则只修改 到期时间 不扣除可用流量

**Comment by ZBrettonYe** [comment]
无法复现
