### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by banxianl08** [ProxyPanel/ProxyPanel#30]
管理页面 到期账账户统计不显示，设置push bear 后，无限报错，设置维护 后台登录不了

**截图**

**Comment by ZBrettonYe** [comment]
第一点 是啥？

**Comment by banxianl08** [comment]
> 第一点 是啥？

![IMG20201001160045](https://user-images.githubusercontent.com/41246205/94783606-818d5880-03ff-11eb-8234-6fc627e28576.jpg)
不显示多少个用户，
