### ISSUE TITLE
域名证书无法2次修改点击提交无反应

### ISSUE THREAD

**Issue by banxianl08** [ProxyPanel/ProxyPanel#31]
**描述你遇到的bug**
简单的描述一下你遇到的bug

**如何复现你的BUG**
为方便找bug，请说明你bug产生的步骤

**截图**

**Comment by ZBrettonYe** [comment]
说中文，看不懂

**Comment by banxianl08** [comment]
编辑域名证书 无法提交，点击无反应
![Screenshot_20201002-234412](https://user-images.githubusercontent.com/41246205/94943001-ab32a680-0509-11eb-8c70-12a39f05d688.png)
