### ISSUE TITLE
线路管理，节点编辑报错

### ISSUE THREAD

**Issue by banxianl08** [ProxyPanel/ProxyPanel#32]
节点编辑报错 
[错误 | Error]
编辑失败：cURL error 28: Failed to connect to api.ip.sb port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

节点授权列表 重置密钥无效

**Comment by ZBrettonYe** [comment]
节点编辑报错 是你服务器的问题l;
大致会访问https://api.ip.sb/geoip/1.1.1.1 这样的链接来更新服务器地理位置
