### ISSUE TITLE
系统设置 节点订阅地址修改不生效

### ISSUE THREAD

**Issue by banxianl08** [ProxyPanel/ProxyPanel#33]
设置/节点设置/节点订阅地址修改不生效

**Comment by ZBrettonYe** [comment]
麻烦在demo站确定以上内容

**Comment by banxianl08** [comment]
真的不生效，必须清除缓存才生效
![Screenshot_20201005-141427](https://user-images.githubusercontent.com/41246205/95045778-519ec780-0715-11eb-8676-7f900209c10c.png)
 在用户订阅复制订阅链接，还是以前的那个，新填入的并没有生效

**Comment by ZBrettonYe** [comment]
每次修改要运行` php artisan route:cache` 来刷新路由
