### ISSUE TITLE
Vnet-v2ray 后端闪退

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#34]
问题一、

说明：下述服务器都属于独立服务器，节点鸡也为独立服务器
1、环境一，Releases 2.4.0（下称R1）
2、环境二，master（下称M1）
3、环境三，vnetpanel 6.6.9（下称V1）

节点鸡部署安装Vnet-V2，R1/V1两套环境能通且正常运行，M1环境下后端一启动10秒内闪退

-----------------------------------------------------------------------------------------

问题二、

R1环境下，Vnet-v2后端掉线，面板能接收反馈同步离线；
M1环境下，Vnet-v2后端掉线，面板刷新N久都没同步离线；

**Comment by ZBrettonYe** [comment]
所以结论是？ 2.4.0版本能用，Master 版本Vnet-V2ray 有问题？

**Comment by zixinote** [comment]
这我就不知道了，我只是验证我的问题而已，对问题提出异议

**Comment by banxianl08** [comment]
> 这我就不知道了，我只是验证我的问题而已，对问题提出异议

 大佬请加我tg @Bigbiubiubiu
