### ISSUE TITLE
可否添加服务器总流量的控制

### ISSUE THREAD

**Issue by 13330863440** [ProxyPanel/ProxyPanel#36]
一般服务器都有总流量限制
可否添加一个功能就是 服务器总流量达到一定设定值时，客户端的节点列表就不再返回该服务器节点

**Comment by ZBrettonYe** [comment]
鸡肋功能，这样面板还要记录你服务器什么时候更新流量的，什么时候截止流量；

总流量这种东西 只要日志没有被自动清除，就会一直叠加
