### ISSUE TITLE
默认站内信推送功能

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#39]
**功能描述 | Feature request description**
当用户完成注册后，或者用户完成购买后，系统能够发送一封站内信息给用户，这样能更贴近用户，当你完成注册，完成购买，我们都有自定义的内容推送给你

**相关资料/想法 | Related documents**

**Comment by zixinote** [comment]
就是能够自定义类型的推送，如完成注册，流量不足，完成购买等，自定义推送站内信的模版，且会员前台能看到这些推送的内容

**Comment by ZBrettonYe** [comment]
能提供对应的文案不？ 中文水平有点不够

还是什么其他地方需要站内通知的

**Comment by zixinote** [comment]
> 能提供对应的文案不？ 中文水平有点不够
> 
> 还是什么其他地方需要站内通知的

我整理下
