### ISSUE TITLE
建议 增加 SOCKs5 对接

### ISSUE THREAD

**Issue by gn73679** [ProxyPanel/ProxyPanel#41]
**功能描述 | Feature request description**
建议 增加 SOCKs5 对接
**相关资料/想法 | Related documents**
 SOCKs5 ， 在目前 来说，还是  满多人在使用的，建议 增加

**Comment by ZBrettonYe** [comment]
超纲了。你先找一个可以和数据库/或者和服务器交互的纯socks5的后端程序再说；
