### ISSUE TITLE
一键订阅

### ISSUE THREAD

**Issue by bickernwong** [ProxyPanel/ProxyPanel#43]
**功能描述 | Feature request description**
代码可以抄VNetpanel v6.4.5里面的

**相关资料/想法 | Related documents**
![捕获](https://user-images.githubusercontent.com/43773706/95745867-6b697d00-0cc8-11eb-94c6-8e8e9cd6b477.JPG)

**Comment by ZBrettonYe** [comment]
有这功能了，下一位
