### ISSUE TITLE
管理后台数据统计的记录消耗/流量消耗不统计数据

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#44]
**描述你遇到的bug**
记录的消耗流量，30日内消耗的流量，里面有数据，但是这里没有数据统计

**如何复现你的BUG**
如下图两个红框的内容

**截图**
![image](https://user-images.githubusercontent.com/63467104/95814186-59c9b900-0d4c-11eb-8e44-62618278ad64.png)

**Comment by ZBrettonYe** [comment]
这2个表都是节点的流量统计， 以 天 为一个记录点
