### ISSUE TITLE
节点流量图表统计问题

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#45]
**描述你遇到的bug**
问题一、11点的图表开始看有流量数据，但是到12点后，11点的数据就不见了。
问题二、节点列表，产生流量 无数据

上述的环境只有一个Vnet-v2ray节点在跑着.
**如何复现你的BUG**
为方便找bug，请说明你bug产生的步骤

**截图**
![image](https://user-images.githubusercontent.com/63467104/95815612-9c40c500-0d4f-11eb-9448-19fe10799bc1.png)
![image](https://user-images.githubusercontent.com/63467104/95815684-cc886380-0d4f-11eb-9bad-b25b18e69215.png)
![image](https://user-images.githubusercontent.com/63467104/95815701-d742f880-0d4f-11eb-9b80-d9752b9f7df2.png)

**Comment by ZBrettonYe** [comment]
感觉唯一可能就是你自动任务没有跑起来，每小时流量没有统计起来
