### ISSUE TITLE
用户流量用完后还可以继续连接使用？

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#47]
**描述你遇到的bug**
如下图所示，流量已经用完了，我依旧可以使用该节点继续跑流量？

**如何复现你的BUG**
下图是我实时监控的统计图，当用户流量剩余为0的时候，我就断开，在连接，重复次数5次，依旧可以正常使用，最后个人更新订阅，依旧继续可以跑

**截图**
![image](https://user-images.githubusercontent.com/63467104/95816169-01e18100-0d51-11eb-91fa-0ef7903891d9.png)

**Comment by ZBrettonYe** [comment]
看你 日志里有没有curl之类的报错

**Comment by ZBrettonYe** [comment]
看你 日志里有没有curl之类的报错

**Comment by ZBrettonYe** [comment]
感觉你提的这几个问题都是一个问题，你自动化任务没有跑起来
