### ISSUE TITLE
无法访问

### ISSUE THREAD

**Issue by garhing** [ProxyPanel/ProxyPanel#49]
**描述你遇到的bug**
简单的描述一下你遇到的bug
执行sh update.sh 后访问面板报错
ErrorException
Trying to get property 'value' of non-object

**如何复现你的BUG**
为方便找bug，请说明你bug产生的步骤
重复执行sh update.sh 同样问题。
**截图**

**Comment by zixinote** [comment]
php artisan migrate

**Comment by garhing** [comment]
> php artisan migrate

Done.Thx
