### ISSUE TITLE
节点设置设置订阅域名添加报错

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#50]
**描述你遇到的bug**
添加订阅域名保存报错，第二次在提交就保存成功。
**如何复现你的BUG**
如下图，

**截图**
![image](https://user-images.githubusercontent.com/63467104/96244449-a6c1bf80-0fd8-11eb-9652-a1eb432e9772.png)

**Comment by ZBrettonYe** [comment]
非面板问题，自己解决服务器问题
