### ISSUE TITLE
系统设置-帐号设置-激活设置选项-选择无效，用户设置禁用代理无效-限速无效

### ISSUE THREAD

**Issue by banxianl08** [ProxyPanel/ProxyPanel#57]
![W~6K6JQJ0SJX%ZJCE2{HDUW](https://user-images.githubusercontent.com/41246205/96349293-3bafe000-10e1-11eb-98c0-98f19d26f4e5.png)

使用VNET后端限速无效。用户禁用代理，依然可以使用

**Comment by ZBrettonYe** [comment]
1. 前者 已修复；
2. 后者看你vnet和面板有没有设置好，vnet里看日志，再到面板里更改节点/用户设置 看有没有推送到vnet；
