### ISSUE TITLE
请求将订阅域名展示功能移动至跟线路节点一起

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#59]
**功能描述 | Feature request description**
希望大佬可以将订阅域名的功能移动至我的线路上展示，因为很多用户购买之后都是去看我的线路，这样的做法看起来比较整体
**相关资料/想法 | Related documents**
![image](https://user-images.githubusercontent.com/63467104/96395896-6771b980-11f8-11eb-9b10-963381507bad.png)

**Comment by ZBrettonYe** [comment]
你可以自行 修改自己的面板显示

**Comment by zixinote** [comment]
我也想自行修改，变量定义了路由，我自行移动后续每次update还要修改，所以才请求你这边调整。

兔姬桑 <notifications@github.com> 于2020年10月19日周一 上午11:30写道：
