### ISSUE TITLE
Quantumult订阅不支持？

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#60]
**描述你遇到的bug**
如题，使用Quantumult订阅返回提示：“远程文件中未包含有效对应类型的配置”，尝试使用这个APP是因为后台订阅有说这个APP有特殊效果，但是订阅不成功。

**如何复现你的BUG**

**截图**
![image](https://user-images.githubusercontent.com/63467104/96396088-e109a780-11f8-11eb-8992-526b23631cf7.png)

**Comment by ZBrettonYe** [comment]
应该是和tls有关的问题
