### ISSUE TITLE
账号已过期 但是不清空用户等级。

### ISSUE THREAD

**Issue by 110560** [ProxyPanel/ProxyPanel#62]
账号已过期。
代理 虽然封禁了
点击线路列表
依然可以看到线路

[定时任务]账号已过期(封禁代理，清空账户) 这里缺一个 
清空用户等级。

**Comment by 110560** [comment]
在没有订单的用户中

Q1 :自动任务只会封禁账号 不会清空账户等级吗？

Q2:  
此账户有可用流量
手动将账户到期日设置 已过期（10月19号）   
没有定时任务封禁账户。代理状态依然启用

Q2在胖虎的面板操作中 
将会自动清空用户可用流量  并且禁用代理

**Comment by 110560** [comment]
![1](https://user-images.githubusercontent.com/32481672/96549819-97958700-12e2-11eb-9cf4-002ef6cab38a.png)
原面板结果
![02](https://user-images.githubusercontent.com/32481672/96550025-e3e0c700-12e2-11eb-8731-88db377405db.png)

**Comment by ZBrettonYe** [comment]
Q2 你自动任务没跑起来，跑起来，扫到了自己会封，还有你玩什么不手动过期的时候顺便也把代理禁了

Q1 下个更新会加上，虽然保留等级并不会造成什么伤害

**Comment by 110560** [comment]
[定时任务]账号已过期(封禁代理，清空账户) | 2020-10-21 00:00:03
-- | -- 你是在零时 扫的  

胖虎10分钟扫一次
