### ISSUE TITLE
账户激活关闭 批量生成的的 账户是未激活

### ISSUE THREAD

**Issue by 110560** [ProxyPanel/ProxyPanel#64]
账户激活关闭 批量生成的的 账户是未激活

**如何复现你的BUG**
账户激活关闭 
点击 批量生成 
账户 未激活

**Comment by 110560** [comment]
> 账户激活关闭 批量生成的 账户是未激活
> 
> **如何复现你的BUG**
> 账户激活关闭
> 点击 批量生成
> 账户 未激活

**Comment by ZBrettonYe** [comment]
激活指邮箱激活
