### ISSUE TITLE
重置日相关问题咨询

### ISSUE THREAD

**Issue by 110560** [ProxyPanel/ProxyPanel#65]
手动设置的流量重置日 
到流量重置日之后  定时任务不会重置流量

用户是手工设置的流量重置日 没有订单....   

建议增加判定  

用户到期日 减去 用户流量重置日 ≥30天 执行清空用户流量

**Comment by 110560** [comment]
才开始用这个面板几天
我不知道。
开发者当前的流量重置日  
是根据什么判定来的  
产生订单能赋予用户流量重置日 但我不知道这个是否正常执行 未测试

手工设置的赋予流量重置日  希望这个判定条件 能实现.....   
我写的那个也不对  
或者直接像胖虎一样基于 重置日来判定  1~30号 自己填入一个日子。

**Comment by 110560** [comment]
日期
![1](https://user-images.githubusercontent.com/32481672/96480968-7c3c6480-126d-11eb-9ceb-992412987da8.png)
流量变动记录里面没有 自动重置流量
![0](https://user-images.githubusercontent.com/32481672/96481015-8cecda80-126d-11eb-8766-3116256be80e.png)

**Comment by ZBrettonYe** [comment]
并没有你说的问题，流量重置的日志是要在流量变动表里 或者 域名/logs 里看的
![image](https://user-images.githubusercontent.com/18015854/96489685-58c7e880-1272-11eb-91a9-1513a3812529.png)

**Comment by 110560** [comment]
用户流量重置日 原本默认为空

我在 2020-10-19 23:57 
将用户流量重置日修改为10月20日,
2020-10-20 00:02 用户的流量还未重置

请教一下
如果手动设置的流量充值日有效
 我大概忘了设置什么东西，导致未执行

**Comment by 110560** [comment]
零点后的记录  麻烦看下日志 我是否忘了设置什么东西  
我还注意到你的图最下面是中文 我的是英语 我是最新版本的Master 不知是不是版本问题
![Uploading 0.png…]()

**Comment by ZBrettonYe** [comment]
2.4 到 2.5.b(即Master版) 就没有改动过重置流量相关的东西；
Log英文是因为有版本更新了Log日志页面；

流量重置前提，账号要有 生效套餐！！！！

麻烦自己看`/app/Console/Commands/DailyJob.php` 了解更多
