### ISSUE TITLE
支付没有回调等其他问题反馈

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#68]
**描述你遇到的bug**
1、支付没有回调日志，付款后一直停留在付款界面；（图4）
2、容易卡在图1的界面，报错（图2）
3、造成大量订单；（图3）

正常填写回调域名等信息，另外服务经常挂起？会员前台，我的账单，有时可以看到取消订支付功能，有时又没有了！

**如何复现你的BUG**
为方便找bug，请说明你bug产生的步骤

**截图**
![image](https://user-images.githubusercontent.com/63467104/96607113-9a1bcf00-132a-11eb-9039-ff455b25e413.png)

![image](https://user-images.githubusercontent.com/63467104/96607379-e2d38800-132a-11eb-8d11-77ddb5f36a28.png)

![image](https://user-images.githubusercontent.com/63467104/96607430-f1ba3a80-132a-11eb-80c9-ddec246e0029.png)

![image](https://user-images.githubusercontent.com/63467104/96608765-5aee7d80-132c-11eb-9e7e-d727896433f3.png)

**Comment by zixinote** [comment]
![image](https://user-images.githubusercontent.com/63467104/96612954-f8e44700-1330-11eb-9cf8-b40321ca4723.png)

**Comment by ZBrettonYe** [comment]
估计你 redis 或者 php redis插件没安装

**Comment by zixinote** [comment]
> 估计你redis或者php redis插件没安装

redis都正常的跑着，你真的不检查下？
