### ISSUE TITLE
数据流量报错

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#69]
**描述你遇到的bug**
最新拉取的版本，正常使用的过程中点会员管理页面出现报错如下图

**如何复现你的BUG**
为方便找bug，请说明你bug产生的步骤

**截图**
![image](https://user-images.githubusercontent.com/63467104/96609204-d819f280-132c-11eb-8572-819081ff2c83.png)

**Comment by ZBrettonYe** [comment]
你的用户订阅表有问题
