### ISSUE TITLE
update更新或者php artisan系统时丢失支付配置？

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#70]
**描述你遇到的bug**
update更新或者使用php artisan等相关命令清除缓存时丢失支付配置？前台提示前往开启支付，后台需要重新选择保存一次配置又回来了。忽略回调域名！

**如何复现你的BUG**
为方便找bug，请说明你bug产生的步骤

**截图**
![image](https://user-images.githubusercontent.com/63467104/96610585-5f1b9a80-132e-11eb-84fe-79f561d6cc92.png)

**Comment by zixinote** [comment]
![image](https://user-images.githubusercontent.com/63467104/96612169-05b46b00-1330-11eb-9e44-f99db4868777.png)

**Comment by ZBrettonYe** [comment]
估计你 redis 或者 php redis插件没安装

**Comment by zixinote** [comment]
redis插件正常啊。
