### ISSUE TITLE
支付没有回调日志

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#71]
**描述你遇到的bug**
redis正常运行，报错如下，没有认真执着的测试，就没有完美的系统，虽然系统正在起步中，应共同进步，理应认真对待每一个问题的反馈。

**如何复现你的BUG**
为方便找bug，请说明你bug产生的步骤

**截图**
![image](https://user-images.githubusercontent.com/63467104/96670332-a6874280-1391-11eb-8913-0285eb22c5de.png)
![image](https://user-images.githubusercontent.com/63467104/96670385-c454a780-1391-11eb-8514-dca39486ba30.png)
![image](https://user-images.githubusercontent.com/63467104/96670249-793a9480-1391-11eb-9d10-a6877ce582b0.png)

**Comment by ZBrettonYe** [comment]
你既然提了，我自然处理了
![image](https://user-images.githubusercontent.com/18015854/96670625-5e1c5480-1392-11eb-80e6-db6a98458fa0.png)
处理结果，没有问题！ 

结束;

`虽然系统正在起步中，应共同进步`

对于你来说是起步，对于我来说，该有的功能都有了， 只是功能多少，好不好用的问题了

**Comment by zixinote** [comment]
本是无意去表达什么，只是想着去做好一件事情，因为很多东西都是从无到有的过程，我也只是反馈使用过程中的问题，同理，起步的意思只是完美系统的起点，你实现的功能本身是足够强大的了，能共同参与测试这套系统是我的荣幸，对于PHP我只是一个小白，言语虽不好亦可能带来别样体悟，勿往心理面去。

**Comment by ZBrettonYe** [comment]
#69 都是一个问题，你服务器的网站路由有问题，
自己看看代码有没有最新，.env里面APP_KEY设置了没有， 跑一遍 `php artisan optimize`

**Comment by ColetteContreras** [comment]
@zixinote 你报的这个问题，我昨天提交的内容应该顺便修复了，这个问题产生的原因是支付平台回调的时候使用的是 POST 而非路由中指定的 GET。

https://github.com/ProxyPanel/ProxyPanel/pull/73/files#diff-193e04aa1705f6f3e484d7efca8f45fe4d19d0ece3b6e6880d3ea070938a1fadR8

**Comment by zixinote** [comment]
@ZBrettonYe 
问题一
当前F2F 同样的配置密钥在Vnet正常使用，但是把密钥贴过来Proxy报错误: sign error, sign type is [RSA2]. msg: [您使用的私钥格式错误，请检查RSA私钥配置]

问题二
麻瓜宝报错如下
  'error_code' => 'PAY_PRICE_ERROR',
  'error' => 'Price amount or currency is not set correctly.',

问题三
Stripe 没有回调日志可看

**Comment by zixinote** [comment]
https://demo.proxypanel.ml/callback/notify?method=paypal 这个有返回数据，其他的都是失败？我不懂这些，只是想请求下意见给个答复。
