### ISSUE TITLE
记录的流量消耗记录BUG？

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#78]
**描述你遇到的bug**
全站就只有我一个会员，没创建过其他会员，想不通账号已删除哪里来的数据。

**如何复现你的BUG**
为方便找bug，请说明你bug产生的步骤

**截图**
![image](https://user-images.githubusercontent.com/63467104/97380519-308b5a00-1902-11eb-8509-eb93fcf52518.png)

**Comment by ZBrettonYe** [comment]
用户ID 找不到 就是 【账号已删除】；

请自行查看数据库里的数据 看看user_id 字段之类的

**Comment by zixinote** [comment]
> 用户ID 找不到 就是 【账号已删除】；
> 
> 请自行查看数据库里的数据 看看user_id 字段之类的

我也想知道用户哪来的数据，我一个用户都没创建过。

**Comment by ZBrettonYe** [comment]
所以说了叫你去看数据库
