### ISSUE TITLE
点击 日志系统-在线IP监控，显示 “访问被拒绝，找不到网页”

### ISSUE THREAD

**Issue by NeedforGit** [ProxyPanel/ProxyPanel#79]
**描述你遇到的bug**

安装的 realse 2.5 版本，PHP7.4，MySQL 5.6

点击 日志系统-在线IP监控，显示 “访问被拒绝，找不到网页”

查看日志显示：

异常请求：https://xxxx.com/admin/log/onlineIPMonitor&ip=&email=&port=&nodeId=2

异常来源：Symfony\Component\HttpKernel\Exception\NotFoundHttpException

**如何复现你的BUG**

除了这个 其他都正常，日志显示 自动化任务也没问题。

---【自动化任务】完成---，耗时0.161秒

**截图**
![微信图片_20201028100054](https://user-images.githubusercontent.com/48271689/97381992-48b0a880-1905-11eb-9f43-a2adfc458368.png)

很喜欢这个面板，求解决！十分感谢！

**Comment by ZBrettonYe** [comment]
Bug 已定位，将在下次更新中修复；


感谢您详细的反馈BUG
