### ISSUE TITLE
用户分组报错

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#83]
**描述你遇到的bug**
新增用户分组报错，创建节点后就出现这个问题，包括之前提的会员信息修改也是，请问这是为什么呢？求大佬给提供一个解决的思路，节点为Vnet

**如何复现你的BUG**
下图来源于演示站

**截图**
![image](https://user-images.githubusercontent.com/63467104/97725709-7403e500-1b09-11eb-9338-58c796e77ead.png)

**Comment by zixinote** [comment]
再次测试了下，好像只有Vnet节点才会出现这个错误

**Comment by ZBrettonYe** [comment]
并不是bug，只是无效节点而已

报错都已经把问题写明了，你的ddr3.com 节点域名没法解析
