### ISSUE TITLE
用户属于任意分组流量抛弃？

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#90]
**描述你遇到的bug**
我有1个节点，我把这个节点添加进AA分组，同样我也把A用户分配到AA分组里面，A用户使用AA分组的所有节点都是无法访问，B用户没有分配进AA组，正常可以访问使用。请问大佬，这是神马情况呢？求答案

**截图**

**Comment by ZBrettonYe** [comment]
需要更详细的描述

**Comment by ZBrettonYe** [comment]
需要更详细描述

**Comment by zixinote** [comment]
> 需要更详细描述
> 
> 什么后端
> 等级是否给了

等级给v1，v2ray

**Comment by ZBrettonYe** [comment]
会不会是节点等级超过v1

**Comment by zixinote** [comment]
> 会不会是节点等级超过v1

与等级没有关系了，测试方式如下：
1、节点等级给0，用户等级给0，归于分组A，无法打开网页；
2、节点等级给0，用户等级给1，归于分组B，无法打开网页；
3、节点等级给1，用户等级给7，归于分组C，无法打开网页；
上诉的方式都是打开就阻断流量了；

如果节点不属于任何分组，那就是正常使用；

**Comment by ZBrettonYe** [comment]
已解决
