### ISSUE TITLE
Warning: This development build of composer is over 60 days old

### ISSUE THREAD

**Issue by wsa01378** [ProxyPanel/ProxyPanel#92]
你好，我反馈一下阿
**如何复现你的BUG**
按照https://proxypanel.gitbook.io/wiki/install/bt 教程，
敲入
composer install --prefer-dist --optimize-autoloader --no-dev
提示
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "/usr/bin/composer self-update" to get the latest version.
Composer could not find a composer.json file in /www/wwwroot/board.etime.vip
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

**Comment by ZBrettonYe** [comment]
google 是个好东西
