### ISSUE TITLE
维护功能问题

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#95]
**描述你遇到的bug**
打开维护，设置维护时间，新开一个窗口在打开管理后台的设置页面，维护状态按钮跟维护时间又自动变回默认的没打开和没设置状态

**如何复现你的BUG**
为方便找bug，请说明你bug产生的步骤

**截图**

**Comment by ZBrettonYe** [comment]
先设置时间，再开维护
