### ISSUE TITLE
logo/统计/客服代码无法保存，苹果账号功能不存在使用性！

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#96]
**描述你遇到的bug**
1、logo/统计代码/客服代码/上传图片或者添加代码后均无法保存，保存后返回又一片空白；

2、后台提供添加苹果账密功能，但是前台又没有这样的功能使用，请大佬帮忙完善它吧；
   （2.1、用户不存在套餐，点击查询账密则提示：您未购买套餐，不予显示，请前往购买；）
   （2.2、用户存在套餐，点击查询账密则显示；）

**Comment by ZBrettonYe** [comment]
1. 不知道

2. 这个自己看 https://app.gitbook.com/@proxypanel/s/wiki/page-modify
