### ISSUE TITLE
Trojan设置中转后用户连接信息里面没有SNI

### ISSUE THREAD

**Issue by geekjy** [ProxyPanel/ProxyPanel#98]
**功能描述 | Feature request description**
Trojan设置中转后用户连接信息里面没有SNI
**相关资料/想法 | Related documents**
没有SNI用户无法连接

**Comment by ZBrettonYe** [comment]
个人不用Trojan 不了解， 能伴我找找Trojan的文档吗？

**Comment by geekjy** [comment]
> 个人不用Trojan 不了解， 能帮我找找Trojan的文档吗？

{
    "run_type": "client",
    "local_addr": "127.0.0.1",
    "local_port": 1080,
    "remote_addr": "中转域名",/*中转VPS的域名*/
    "remote_port": 51262,/*中转端口*/
    "password": [
        "连接密码"
    ],
    "log_level": 1,
    "ssl": {
        "verify": true,
        "verify_hostname": true,
        "cert": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:AES128-SHA:AES256-SHA:DES-CBC3-SHA",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "sni": "真实连接域名",/*真实的连接域名，端口443在haproxy里面配置好了*/
        "alpn": [
            "h2",
            "http/1.1"
        ],
        "reuse_session": true,
        "session_ticket": false,
        "curves": ""
    },
    "tcp": {
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
    }
}

**Comment by geekjy** [comment]
现在的面板设置了trojan中转以后用户页面中没有SNI来显示，"remote_addr": "中转域名",/中转VPS的域名/
"remote_port": 51262,/中转端口/
"password": "连接密码"
"sni": "真实连接域名",/真实的连接域名，端口443在haproxy里面配置好了/
应该是这样子才能让用户连接上
