### ISSUE TITLE
用户订阅触发封禁后无法解封？

### ISSUE THREAD

**Issue by zixinote** [ProxyPanel/ProxyPanel#99]
**描述你遇到的bug**
如题，我24小时内连续请求超过系统设置的值，然后没有地方可以控制解封么？

**如何复现你的BUG**
为方便找bug，请说明你bug产生的步骤

**截图**

**Comment by zixinote** [comment]
只能数据库修改

**Comment by ZBrettonYe** [comment]
xxxxxxxxxx/admin/subscribe
![image](https://user-images.githubusercontent.com/18015854/101842790-c82bcb80-3b83-11eb-85c9-a4da1e577093.png)

要么自己在系统设置修改封禁触发值/ 过一段时间后， 再访问上面的地址 去解封
